/*
 * hacca - C Toolkit for the HL7 Protocol
 *
 * Warning: This file was automatically generated by [hawk], please do not edit.
 *          Thu 25 Jun 19:02:37 CEST 2020
 *
 * R. Carbone (rocco@tecsiel.it)
 * Jun 2020
 *
 * SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * This file was developed as part of the ongoing activities related
 * to the design, implementation and execution of interoperability tests
 * between hacca-based versus AurigaHL7-based applications.
 *
 * In more details I decided to extend AurigaHL7 C++ Library with header files
 * implementing HL7 structures of the version 2.8.1 of the protocol (April 2014)
 * because the version 2.4 distributed with AurigaHL7 is a bit outdated (October 2000).
 *
 * All files in this fork was automatically generated by hacca-based tool [hawk]
 * and strictly follow the syntax and convention originally defined
 * by Auriga HL7 C++ Library just as form of continuity, convenience
 * and respect for their superb work.
 */


#ifndef __CSU_C09__281_H__
#define __CSU_C09__281_H__

#include "../../common/Util.h"
#include "../segment/ARV.h"
#include "../segment/CSP.h"
#include "../segment/CSR.h"
#include "../segment/CSS.h"
#include "../segment/MSH.h"
#include "../segment/NTE.h"
#include "../segment/OBR.h"
#include "../segment/OBX.h"
#include "../segment/ORC.h"
#include "../segment/PD1.h"
#include "../segment/PID.h"
#include "../segment/PRT.h"
#include "../segment/PV1.h"
#include "../segment/PV2.h"
#include "../segment/RXA.h"
#include "../segment/RXR.h"
#include "../segment/SFT.h"
#include "../segment/TQ1.h"
#include "../segment/TQ2.h"
#include "../segment/UAC.h"

namespace HL7_281 {

/* Internal structures/groups */
struct CSU_C09_PATIENT; /* PATIENT */
struct CSU_C09_VISIT; /* VISIT */
struct CSU_C09_STUDY_PHASE; /* STUDY_PHASE */
struct CSU_C09_STUDY_SCHEDULE; /* STUDY_SCHEDULE */
struct CSU_C09_STUDY_OBSERVATION; /* STUDY_OBSERVATION */
struct CSU_C09_STUDY_PHARM; /* STUDY_PHARM */
struct CSU_C09_ORCPRT; /* ORCPRT */
struct CSU_C09_TIMING_QTY; /* TIMING_QTY */
struct CSU_C09_ORCPRT; /* ORCPRT */
struct CSU_C09_TIMING_QTY; /* TIMING_QTY */
struct CSU_C09_COMMON_ORDER; /* COMMON_ORDER */
struct CSU_C09_RX_ADMIN; /* RX_ADMIN */

/* PATIENT */
struct CSU_C09_PATIENT : public HL7Group {
  CSU_C09_PATIENT() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    CSU_C09_ARV_1,
    CSU_C09_CSR_2,
    CSU_C09_CSU_C09_STUDY_PHASE_3,
    CSU_C09_CSU_C09_VISIT_4,
    CSU_C09_NTE_5,
    CSU_C09_PD1_6,
    CSU_C09_PID_7,
    CSU_C09_PRT_8,
    FIELD_ID_MAX
  };

  const char* className() const { return "CSU_C09_PATIENT"; }
  CSU_C09_PATIENT* create() const { return new CSU_C09_PATIENT(); }

 private:
  /* Initialize object */
  void init() {
    setName("CSU_C09.PATIENT");
    addObject<ARV>(CSU_C09_ARV_1, "ARV.1", HL7::optional, HL7::repetition_on);
    addObject<CSR>(CSU_C09_CSR_2, "CSR.2", HL7::optional, HL7::repetition_on);
    addObject<CSU_C09_STUDY_PHASE>(CSU_C09_CSU_C09_STUDY_PHASE_3, "CSU_C09_STUDY_PHASE.3", HL7::optional, HL7::repetition_on);
    addObject<CSU_C09_VISIT>(CSU_C09_CSU_C09_VISIT_4, "CSU_C09_VISIT.4", HL7::optional, HL7::repetition_on);
    addObject<NTE>(CSU_C09_NTE_5, "NTE.5", HL7::optional, HL7::repetition_on);
    addObject<PD1>(CSU_C09_PD1_6, "PD1.6", HL7::optional, HL7::repetition_on);
    addObject<PID>(CSU_C09_PID_7, "PID.7", HL7::optional, HL7::repetition_on);
    addObject<PRT>(CSU_C09_PRT_8, "PRT.8", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  ARV* getARV_1(size_t index = 0) {
    return (ARV*)this->getObjectSafe(index, CSU_C09_ARV_1);
  }
  CSR* getCSR_2(size_t index = 0) {
    return (CSR*)this->getObjectSafe(index, CSU_C09_CSR_2);
  }
  CSU_C09_STUDY_PHASE* getCSU_C09_STUDY_PHASE_3(size_t index = 0) {
    return (CSU_C09_STUDY_PHASE*)this->getObjectSafe(index, CSU_C09_CSU_C09_STUDY_PHASE_3);
  }
  CSU_C09_VISIT* getCSU_C09_VISIT_4(size_t index = 0) {
    return (CSU_C09_VISIT*)this->getObjectSafe(index, CSU_C09_CSU_C09_VISIT_4);
  }
  NTE* getNTE_5(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, CSU_C09_NTE_5);
  }
  PD1* getPD1_6(size_t index = 0) {
    return (PD1*)this->getObjectSafe(index, CSU_C09_PD1_6);
  }
  PID* getPID_7(size_t index = 0) {
    return (PID*)this->getObjectSafe(index, CSU_C09_PID_7);
  }
  PRT* getPRT_8(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_8);
  }

  /* Checker list */
  bool isARV_1(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_ARV_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isCSR_2(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_CSR_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isCSU_C09_STUDY_PHASE_3(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_CSU_C09_STUDY_PHASE_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isCSU_C09_VISIT_4(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_CSU_C09_VISIT_4) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_5(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_NTE_5) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPD1_6(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PD1_6) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPID_7(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PID_7) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_8(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_8) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* CSU_C09_PATIENT */

/* VISIT */
struct CSU_C09_VISIT : public HL7Group {
  CSU_C09_VISIT() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    CSU_C09_PRT_1,
    CSU_C09_PV1_2,
    CSU_C09_PV2_3,
    FIELD_ID_MAX
  };

  const char* className() const { return "CSU_C09_VISIT"; }
  CSU_C09_VISIT* create() const { return new CSU_C09_VISIT(); }

 private:
  /* Initialize object */
  void init() {
    setName("CSU_C09.VISIT");
    addObject<PRT>(CSU_C09_PRT_1, "PRT.1", HL7::optional, HL7::repetition_on);
    addObject<PV1>(CSU_C09_PV1_2, "PV1.2", HL7::optional, HL7::repetition_on);
    addObject<PV2>(CSU_C09_PV2_3, "PV2.3", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  PRT* getPRT_1(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_1);
  }
  PV1* getPV1_2(size_t index = 0) {
    return (PV1*)this->getObjectSafe(index, CSU_C09_PV1_2);
  }
  PV2* getPV2_3(size_t index = 0) {
    return (PV2*)this->getObjectSafe(index, CSU_C09_PV2_3);
  }

  /* Checker list */
  bool isPRT_1(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPV1_2(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PV1_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPV2_3(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PV2_3) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* CSU_C09_VISIT */

/* STUDY_PHASE */
struct CSU_C09_STUDY_PHASE : public HL7Group {
  CSU_C09_STUDY_PHASE() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    CSU_C09_CSP_1,
    CSU_C09_CSU_C09_STUDY_SCHEDULE_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "CSU_C09_STUDY_PHASE"; }
  CSU_C09_STUDY_PHASE* create() const { return new CSU_C09_STUDY_PHASE(); }

 private:
  /* Initialize object */
  void init() {
    setName("CSU_C09.STUDY_PHASE");
    addObject<CSP>(CSU_C09_CSP_1, "CSP.1", HL7::optional, HL7::repetition_on);
    addObject<CSU_C09_STUDY_SCHEDULE>(CSU_C09_CSU_C09_STUDY_SCHEDULE_2, "CSU_C09_STUDY_SCHEDULE.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  CSP* getCSP_1(size_t index = 0) {
    return (CSP*)this->getObjectSafe(index, CSU_C09_CSP_1);
  }
  CSU_C09_STUDY_SCHEDULE* getCSU_C09_STUDY_SCHEDULE_2(size_t index = 0) {
    return (CSU_C09_STUDY_SCHEDULE*)this->getObjectSafe(index, CSU_C09_CSU_C09_STUDY_SCHEDULE_2);
  }

  /* Checker list */
  bool isCSP_1(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_CSP_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isCSU_C09_STUDY_SCHEDULE_2(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_CSU_C09_STUDY_SCHEDULE_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* CSU_C09_STUDY_PHASE */

/* STUDY_SCHEDULE */
struct CSU_C09_STUDY_SCHEDULE : public HL7Group {
  CSU_C09_STUDY_SCHEDULE() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    CSU_C09_CSS_1,
    CSU_C09_CSU_C09_STUDY_OBSERVATION_2,
    CSU_C09_CSU_C09_STUDY_PHARM_3,
    FIELD_ID_MAX
  };

  const char* className() const { return "CSU_C09_STUDY_SCHEDULE"; }
  CSU_C09_STUDY_SCHEDULE* create() const { return new CSU_C09_STUDY_SCHEDULE(); }

 private:
  /* Initialize object */
  void init() {
    setName("CSU_C09.STUDY_SCHEDULE");
    addObject<CSS>(CSU_C09_CSS_1, "CSS.1", HL7::optional, HL7::repetition_on);
    addObject<CSU_C09_STUDY_OBSERVATION>(CSU_C09_CSU_C09_STUDY_OBSERVATION_2, "CSU_C09_STUDY_OBSERVATION.2", HL7::optional, HL7::repetition_on);
    addObject<CSU_C09_STUDY_PHARM>(CSU_C09_CSU_C09_STUDY_PHARM_3, "CSU_C09_STUDY_PHARM.3", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  CSS* getCSS_1(size_t index = 0) {
    return (CSS*)this->getObjectSafe(index, CSU_C09_CSS_1);
  }
  CSU_C09_STUDY_OBSERVATION* getCSU_C09_STUDY_OBSERVATION_2(size_t index = 0) {
    return (CSU_C09_STUDY_OBSERVATION*)this->getObjectSafe(index, CSU_C09_CSU_C09_STUDY_OBSERVATION_2);
  }
  CSU_C09_STUDY_PHARM* getCSU_C09_STUDY_PHARM_3(size_t index = 0) {
    return (CSU_C09_STUDY_PHARM*)this->getObjectSafe(index, CSU_C09_CSU_C09_STUDY_PHARM_3);
  }

  /* Checker list */
  bool isCSS_1(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_CSS_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isCSU_C09_STUDY_OBSERVATION_2(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_CSU_C09_STUDY_OBSERVATION_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isCSU_C09_STUDY_PHARM_3(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_CSU_C09_STUDY_PHARM_3) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* CSU_C09_STUDY_SCHEDULE */

/* STUDY_OBSERVATION */
struct CSU_C09_STUDY_OBSERVATION : public HL7Group {
  CSU_C09_STUDY_OBSERVATION() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    CSU_C09_CSU_C09_ORCPRT_1,
    CSU_C09_CSU_C09_TIMING_QTY_2,
    CSU_C09_OBR_3,
    CSU_C09_OBX_4,
    CSU_C09_PRT_5,
    FIELD_ID_MAX
  };

  const char* className() const { return "CSU_C09_STUDY_OBSERVATION"; }
  CSU_C09_STUDY_OBSERVATION* create() const { return new CSU_C09_STUDY_OBSERVATION(); }

 private:
  /* Initialize object */
  void init() {
    setName("CSU_C09.STUDY_OBSERVATION");
    addObject<CSU_C09_ORCPRT>(CSU_C09_CSU_C09_ORCPRT_1, "CSU_C09_ORCPRT.1", HL7::optional, HL7::repetition_on);
    addObject<CSU_C09_TIMING_QTY>(CSU_C09_CSU_C09_TIMING_QTY_2, "CSU_C09_TIMING_QTY.2", HL7::optional, HL7::repetition_on);
    addObject<OBR>(CSU_C09_OBR_3, "OBR.3", HL7::optional, HL7::repetition_on);
    addObject<OBX>(CSU_C09_OBX_4, "OBX.4", HL7::optional, HL7::repetition_on);
    addObject<PRT>(CSU_C09_PRT_5, "PRT.5", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  CSU_C09_ORCPRT* getCSU_C09_ORCPRT_1(size_t index = 0) {
    return (CSU_C09_ORCPRT*)this->getObjectSafe(index, CSU_C09_CSU_C09_ORCPRT_1);
  }
  CSU_C09_TIMING_QTY* getCSU_C09_TIMING_QTY_2(size_t index = 0) {
    return (CSU_C09_TIMING_QTY*)this->getObjectSafe(index, CSU_C09_CSU_C09_TIMING_QTY_2);
  }
  OBR* getOBR_3(size_t index = 0) {
    return (OBR*)this->getObjectSafe(index, CSU_C09_OBR_3);
  }
  OBX* getOBX_4(size_t index = 0) {
    return (OBX*)this->getObjectSafe(index, CSU_C09_OBX_4);
  }
  PRT* getPRT_5(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_5);
  }

  /* Checker list */
  bool isCSU_C09_ORCPRT_1(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_CSU_C09_ORCPRT_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isCSU_C09_TIMING_QTY_2(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_CSU_C09_TIMING_QTY_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBR_3(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_OBR_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBX_4(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_OBX_4) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_5(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_5) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* CSU_C09_STUDY_OBSERVATION */

/* STUDY_PHARM */
struct CSU_C09_STUDY_PHARM : public HL7Group {
  CSU_C09_STUDY_PHARM() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    CSU_C09_CSU_C09_COMMON_ORDER_1,
    CSU_C09_CSU_C09_RX_ADMIN_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "CSU_C09_STUDY_PHARM"; }
  CSU_C09_STUDY_PHARM* create() const { return new CSU_C09_STUDY_PHARM(); }

 private:
  /* Initialize object */
  void init() {
    setName("CSU_C09.STUDY_PHARM");
    addObject<CSU_C09_COMMON_ORDER>(CSU_C09_CSU_C09_COMMON_ORDER_1, "CSU_C09_COMMON_ORDER.1", HL7::optional, HL7::repetition_on);
    addObject<CSU_C09_RX_ADMIN>(CSU_C09_CSU_C09_RX_ADMIN_2, "CSU_C09_RX_ADMIN.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  CSU_C09_COMMON_ORDER* getCSU_C09_COMMON_ORDER_1(size_t index = 0) {
    return (CSU_C09_COMMON_ORDER*)this->getObjectSafe(index, CSU_C09_CSU_C09_COMMON_ORDER_1);
  }
  CSU_C09_RX_ADMIN* getCSU_C09_RX_ADMIN_2(size_t index = 0) {
    return (CSU_C09_RX_ADMIN*)this->getObjectSafe(index, CSU_C09_CSU_C09_RX_ADMIN_2);
  }

  /* Checker list */
  bool isCSU_C09_COMMON_ORDER_1(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_CSU_C09_COMMON_ORDER_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isCSU_C09_RX_ADMIN_2(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_CSU_C09_RX_ADMIN_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* CSU_C09_STUDY_PHARM */

/* ORCPRT */
struct CSU_C09_ORCPRT : public HL7Group {
  CSU_C09_ORCPRT() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    CSU_C09_ORC_1,
    CSU_C09_PRT_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "CSU_C09_ORCPRT"; }
  CSU_C09_ORCPRT* create() const { return new CSU_C09_ORCPRT(); }

 private:
  /* Initialize object */
  void init() {
    setName("CSU_C09.ORCPRT");
    addObject<ORC>(CSU_C09_ORC_1, "ORC.1", HL7::optional, HL7::repetition_on);
    addObject<PRT>(CSU_C09_PRT_2, "PRT.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  ORC* getORC_1(size_t index = 0) {
    return (ORC*)this->getObjectSafe(index, CSU_C09_ORC_1);
  }
  PRT* getPRT_2(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_2);
  }

  /* Checker list */
  bool isORC_1(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_ORC_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_2(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* CSU_C09_ORCPRT */

/* TIMING_QTY */
struct CSU_C09_TIMING_QTY : public HL7Group {
  CSU_C09_TIMING_QTY() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    CSU_C09_TQ1_1,
    CSU_C09_TQ2_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "CSU_C09_TIMING_QTY"; }
  CSU_C09_TIMING_QTY* create() const { return new CSU_C09_TIMING_QTY(); }

 private:
  /* Initialize object */
  void init() {
    setName("CSU_C09.TIMING_QTY");
    addObject<TQ1>(CSU_C09_TQ1_1, "TQ1.1", HL7::optional, HL7::repetition_on);
    addObject<TQ2>(CSU_C09_TQ2_2, "TQ2.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  TQ1* getTQ1_1(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, CSU_C09_TQ1_1);
  }
  TQ2* getTQ2_2(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, CSU_C09_TQ2_2);
  }

  /* Checker list */
  bool isTQ1_1(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_TQ1_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_2(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_TQ2_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* CSU_C09_TIMING_QTY */

/* COMMON_ORDER */
struct CSU_C09_COMMON_ORDER : public HL7Group {
  CSU_C09_COMMON_ORDER() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    CSU_C09_ORC_1,
    CSU_C09_PRT_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "CSU_C09_COMMON_ORDER"; }
  CSU_C09_COMMON_ORDER* create() const { return new CSU_C09_COMMON_ORDER(); }

 private:
  /* Initialize object */
  void init() {
    setName("CSU_C09.COMMON_ORDER");
    addObject<ORC>(CSU_C09_ORC_1, "ORC.1", HL7::optional, HL7::repetition_on);
    addObject<PRT>(CSU_C09_PRT_2, "PRT.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  ORC* getORC_1(size_t index = 0) {
    return (ORC*)this->getObjectSafe(index, CSU_C09_ORC_1);
  }
  PRT* getPRT_2(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_2);
  }

  /* Checker list */
  bool isORC_1(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_ORC_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_2(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* CSU_C09_COMMON_ORDER */

/* RX_ADMIN */
struct CSU_C09_RX_ADMIN : public HL7Group {
  CSU_C09_RX_ADMIN() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    CSU_C09_PRT_1,
    CSU_C09_RXA_2,
    CSU_C09_RXR_3,
    FIELD_ID_MAX
  };

  const char* className() const { return "CSU_C09_RX_ADMIN"; }
  CSU_C09_RX_ADMIN* create() const { return new CSU_C09_RX_ADMIN(); }

 private:
  /* Initialize object */
  void init() {
    setName("CSU_C09.RX_ADMIN");
    addObject<PRT>(CSU_C09_PRT_1, "PRT.1", HL7::optional, HL7::repetition_on);
    addObject<RXA>(CSU_C09_RXA_2, "RXA.2", HL7::optional, HL7::repetition_on);
    addObject<RXR>(CSU_C09_RXR_3, "RXR.3", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  PRT* getPRT_1(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_1);
  }
  RXA* getRXA_2(size_t index = 0) {
    return (RXA*)this->getObjectSafe(index, CSU_C09_RXA_2);
  }
  RXR* getRXR_3(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, CSU_C09_RXR_3);
  }

  /* Checker list */
  bool isPRT_1(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXA_2(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_RXA_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_3(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_RXR_3) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* CSU_C09_RX_ADMIN */

/* CSU_C09 */
struct CSU_C09 : public HL7Message {
  CSU_C09() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    CSU_C09_MSH_1,
    CSU_C09_SFT_2,
    CSU_C09_UAC_3,
    CSU_C09_PID_5,
    CSU_C09_PD1_6,
    CSU_C09_PRT_7,
    CSU_C09_ARV_8,
    CSU_C09_NTE_9,
    CSU_C09_CSR_11,
    CSU_C09_PV1_13,
    CSU_C09_PV2_14,
    CSU_C09_PRT_15,
    CSU_C09_PV1_16,
    CSU_C09_PV2_17,
    CSU_C09_PRT_18,
    CSU_C09_CSP_19,
    CSU_C09_CSS_21,
    CSU_C09_OBR_25,
    CSU_C09_PRT_26,
    CSU_C09_OBX_28,
    CSU_C09_PRT_29,
    CSU_C09_ORC_30,
    CSU_C09_PRT_31,
    CSU_C09_ORC_32,
    CSU_C09_PRT_33,
    CSU_C09_TQ1_34,
    CSU_C09_TQ2_35,
    CSU_C09_OBR_37,
    CSU_C09_PRT_38,
    CSU_C09_OBX_40,
    CSU_C09_PRT_41,
    CSU_C09_ORC_44,
    CSU_C09_PRT_45,
    CSU_C09_ORC_46,
    CSU_C09_PRT_47,
    CSU_C09_TQ1_48,
    CSU_C09_TQ2_49,
    CSU_C09_ORC_50,
    CSU_C09_PRT_51,
    CSU_C09_TQ1_52,
    CSU_C09_TQ2_53,
    CSU_C09_ORC_54,
    CSU_C09_PRT_55,
    CSU_C09_ORC_56,
    CSU_C09_PRT_57,
    CSU_C09_TQ1_58,
    CSU_C09_TQ2_59,
    CSU_C09_ORC_60,
    CSU_C09_PRT_61,
    CSU_C09_RXA_62,
    CSU_C09_RXR_63,
    CSU_C09_PRT_64,
    FIELD_ID_MAX
  };

  const char* className() const { return "CSU_C09"; }
  CSU_C09* create() const { return new CSU_C09(); }

 private:
  /* Initialize object */
  void init() {
    setName("CSU_C09");
    addObject<MSH>(CSU_C09_MSH_1, "MSH.1", HL7::initialized, HL7::repetition_off);
    addObject<SFT>(CSU_C09_SFT_2, "SFT.2", HL7::optional, HL7::repetition_on);
    addObject<UAC>(CSU_C09_UAC_3, "UAC.3", HL7::optional, HL7::repetition_off);
    addObject<PID>(CSU_C09_PID_5, "PID.5", HL7::initialized, HL7::repetition_off);
    addObject<PD1>(CSU_C09_PD1_6, "PD1.6", HL7::optional, HL7::repetition_off);
    addObject<PRT>(CSU_C09_PRT_7, "PRT.7", HL7::optional, HL7::repetition_off);
    addObject<ARV>(CSU_C09_ARV_8, "ARV.8", HL7::optional, HL7::repetition_off);
    addObject<NTE>(CSU_C09_NTE_9, "NTE.9", HL7::optional, HL7::repetition_off);
    addObject<CSR>(CSU_C09_CSR_11, "CSR.11", HL7::initialized, HL7::repetition_off);
    addObject<PV1>(CSU_C09_PV1_13, "PV1.13", HL7::initialized, HL7::repetition_off);
    addObject<PV2>(CSU_C09_PV2_14, "PV2.14", HL7::optional, HL7::repetition_off);
    addObject<PRT>(CSU_C09_PRT_15, "PRT.15", HL7::optional, HL7::repetition_off);
    addObject<PV1>(CSU_C09_PV1_16, "PV1.16", HL7::initialized, HL7::repetition_off);
    addObject<PV2>(CSU_C09_PV2_17, "PV2.17", HL7::optional, HL7::repetition_off);
    addObject<PRT>(CSU_C09_PRT_18, "PRT.18", HL7::optional, HL7::repetition_off);
    addObject<CSP>(CSU_C09_CSP_19, "CSP.19", HL7::optional, HL7::repetition_off);
    addObject<CSS>(CSU_C09_CSS_21, "CSS.21", HL7::optional, HL7::repetition_off);
    addObject<OBR>(CSU_C09_OBR_25, "OBR.25", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(CSU_C09_PRT_26, "PRT.26", HL7::optional, HL7::repetition_off);
    addObject<OBX>(CSU_C09_OBX_28, "OBX.28", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(CSU_C09_PRT_29, "PRT.29", HL7::optional, HL7::repetition_off);
    addObject<ORC>(CSU_C09_ORC_30, "ORC.30", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(CSU_C09_PRT_31, "PRT.31", HL7::optional, HL7::repetition_off);
    addObject<ORC>(CSU_C09_ORC_32, "ORC.32", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(CSU_C09_PRT_33, "PRT.33", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(CSU_C09_TQ1_34, "TQ1.34", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(CSU_C09_TQ2_35, "TQ2.35", HL7::optional, HL7::repetition_off);
    addObject<OBR>(CSU_C09_OBR_37, "OBR.37", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(CSU_C09_PRT_38, "PRT.38", HL7::optional, HL7::repetition_off);
    addObject<OBX>(CSU_C09_OBX_40, "OBX.40", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(CSU_C09_PRT_41, "PRT.41", HL7::optional, HL7::repetition_off);
    addObject<ORC>(CSU_C09_ORC_44, "ORC.44", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(CSU_C09_PRT_45, "PRT.45", HL7::optional, HL7::repetition_off);
    addObject<ORC>(CSU_C09_ORC_46, "ORC.46", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(CSU_C09_PRT_47, "PRT.47", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(CSU_C09_TQ1_48, "TQ1.48", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(CSU_C09_TQ2_49, "TQ2.49", HL7::optional, HL7::repetition_off);
    addObject<ORC>(CSU_C09_ORC_50, "ORC.50", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(CSU_C09_PRT_51, "PRT.51", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(CSU_C09_TQ1_52, "TQ1.52", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(CSU_C09_TQ2_53, "TQ2.53", HL7::optional, HL7::repetition_off);
    addObject<ORC>(CSU_C09_ORC_54, "ORC.54", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(CSU_C09_PRT_55, "PRT.55", HL7::optional, HL7::repetition_off);
    addObject<ORC>(CSU_C09_ORC_56, "ORC.56", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(CSU_C09_PRT_57, "PRT.57", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(CSU_C09_TQ1_58, "TQ1.58", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(CSU_C09_TQ2_59, "TQ2.59", HL7::optional, HL7::repetition_off);
    addObject<ORC>(CSU_C09_ORC_60, "ORC.60", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(CSU_C09_PRT_61, "PRT.61", HL7::optional, HL7::repetition_off);
    addObject<RXA>(CSU_C09_RXA_62, "RXA.62", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(CSU_C09_RXR_63, "RXR.63", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(CSU_C09_PRT_64, "PRT.64", HL7::optional, HL7::repetition_off);
  }

 public:
  /* Getters list */
  MSH* getMSH_1(size_t index = 0) {
    return (MSH*)this->getObjectSafe(index, CSU_C09_MSH_1);
  }
  SFT* getSFT_2(size_t index = 0) {
    return (SFT*)this->getObjectSafe(index, CSU_C09_SFT_2);
  }
  UAC* getUAC_3(size_t index = 0) {
    return (UAC*)this->getObjectSafe(index, CSU_C09_UAC_3);
  }
  PID* getPID_5(size_t index = 0) {
    return (PID*)this->getObjectSafe(index, CSU_C09_PID_5);
  }
  PD1* getPD1_6(size_t index = 0) {
    return (PD1*)this->getObjectSafe(index, CSU_C09_PD1_6);
  }
  PRT* getPRT_7(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_7);
  }
  ARV* getARV_8(size_t index = 0) {
    return (ARV*)this->getObjectSafe(index, CSU_C09_ARV_8);
  }
  NTE* getNTE_9(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, CSU_C09_NTE_9);
  }
  CSR* getCSR_11(size_t index = 0) {
    return (CSR*)this->getObjectSafe(index, CSU_C09_CSR_11);
  }
  PV1* getPV1_13(size_t index = 0) {
    return (PV1*)this->getObjectSafe(index, CSU_C09_PV1_13);
  }
  PV2* getPV2_14(size_t index = 0) {
    return (PV2*)this->getObjectSafe(index, CSU_C09_PV2_14);
  }
  PRT* getPRT_15(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_15);
  }
  PV1* getPV1_16(size_t index = 0) {
    return (PV1*)this->getObjectSafe(index, CSU_C09_PV1_16);
  }
  PV2* getPV2_17(size_t index = 0) {
    return (PV2*)this->getObjectSafe(index, CSU_C09_PV2_17);
  }
  PRT* getPRT_18(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_18);
  }
  CSP* getCSP_19(size_t index = 0) {
    return (CSP*)this->getObjectSafe(index, CSU_C09_CSP_19);
  }
  CSS* getCSS_21(size_t index = 0) {
    return (CSS*)this->getObjectSafe(index, CSU_C09_CSS_21);
  }
  OBR* getOBR_25(size_t index = 0) {
    return (OBR*)this->getObjectSafe(index, CSU_C09_OBR_25);
  }
  PRT* getPRT_26(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_26);
  }
  OBX* getOBX_28(size_t index = 0) {
    return (OBX*)this->getObjectSafe(index, CSU_C09_OBX_28);
  }
  PRT* getPRT_29(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_29);
  }
  ORC* getORC_30(size_t index = 0) {
    return (ORC*)this->getObjectSafe(index, CSU_C09_ORC_30);
  }
  PRT* getPRT_31(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_31);
  }
  ORC* getORC_32(size_t index = 0) {
    return (ORC*)this->getObjectSafe(index, CSU_C09_ORC_32);
  }
  PRT* getPRT_33(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_33);
  }
  TQ1* getTQ1_34(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, CSU_C09_TQ1_34);
  }
  TQ2* getTQ2_35(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, CSU_C09_TQ2_35);
  }
  OBR* getOBR_37(size_t index = 0) {
    return (OBR*)this->getObjectSafe(index, CSU_C09_OBR_37);
  }
  PRT* getPRT_38(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_38);
  }
  OBX* getOBX_40(size_t index = 0) {
    return (OBX*)this->getObjectSafe(index, CSU_C09_OBX_40);
  }
  PRT* getPRT_41(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_41);
  }
  ORC* getORC_44(size_t index = 0) {
    return (ORC*)this->getObjectSafe(index, CSU_C09_ORC_44);
  }
  PRT* getPRT_45(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_45);
  }
  ORC* getORC_46(size_t index = 0) {
    return (ORC*)this->getObjectSafe(index, CSU_C09_ORC_46);
  }
  PRT* getPRT_47(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_47);
  }
  TQ1* getTQ1_48(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, CSU_C09_TQ1_48);
  }
  TQ2* getTQ2_49(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, CSU_C09_TQ2_49);
  }
  ORC* getORC_50(size_t index = 0) {
    return (ORC*)this->getObjectSafe(index, CSU_C09_ORC_50);
  }
  PRT* getPRT_51(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_51);
  }
  TQ1* getTQ1_52(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, CSU_C09_TQ1_52);
  }
  TQ2* getTQ2_53(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, CSU_C09_TQ2_53);
  }
  ORC* getORC_54(size_t index = 0) {
    return (ORC*)this->getObjectSafe(index, CSU_C09_ORC_54);
  }
  PRT* getPRT_55(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_55);
  }
  ORC* getORC_56(size_t index = 0) {
    return (ORC*)this->getObjectSafe(index, CSU_C09_ORC_56);
  }
  PRT* getPRT_57(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_57);
  }
  TQ1* getTQ1_58(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, CSU_C09_TQ1_58);
  }
  TQ2* getTQ2_59(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, CSU_C09_TQ2_59);
  }
  ORC* getORC_60(size_t index = 0) {
    return (ORC*)this->getObjectSafe(index, CSU_C09_ORC_60);
  }
  PRT* getPRT_61(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_61);
  }
  RXA* getRXA_62(size_t index = 0) {
    return (RXA*)this->getObjectSafe(index, CSU_C09_RXA_62);
  }
  RXR* getRXR_63(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, CSU_C09_RXR_63);
  }
  PRT* getPRT_64(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, CSU_C09_PRT_64);
  }

  /* Checker list */
  bool isMSH_1(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_MSH_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isSFT_2(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_SFT_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isUAC_3(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_UAC_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPID_5(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PID_5) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPD1_6(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PD1_6) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_7(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_7) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isARV_8(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_ARV_8) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_9(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_NTE_9) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isCSR_11(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_CSR_11) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPV1_13(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PV1_13) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPV2_14(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PV2_14) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_15(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_15) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPV1_16(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PV1_16) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPV2_17(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PV2_17) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_18(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_18) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isCSP_19(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_CSP_19) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isCSS_21(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_CSS_21) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBR_25(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_OBR_25) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_26(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_26) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBX_28(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_OBX_28) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_29(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_29) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isORC_30(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_ORC_30) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_31(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_31) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isORC_32(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_ORC_32) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_33(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_33) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_34(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_TQ1_34) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_35(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_TQ2_35) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBR_37(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_OBR_37) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_38(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_38) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBX_40(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_OBX_40) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_41(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_41) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isORC_44(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_ORC_44) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_45(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_45) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isORC_46(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_ORC_46) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_47(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_47) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_48(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_TQ1_48) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_49(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_TQ2_49) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isORC_50(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_ORC_50) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_51(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_51) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_52(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_TQ1_52) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_53(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_TQ2_53) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isORC_54(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_ORC_54) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_55(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_55) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isORC_56(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_ORC_56) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_57(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_57) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_58(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_TQ1_58) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_59(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_TQ2_59) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isORC_60(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_ORC_60) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_61(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_61) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXA_62(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_RXA_62) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_63(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_RXR_63) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_64(size_t index = 0) {
    try {
      return this->getObject(index, CSU_C09_PRT_64) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* CSU_C09_ */
} /* namespace HL7_281 */
#endif /*  __CSU_C09__281_H__ */
