/*
 * hacca - C Toolkit for the HL7 Protocol
 *
 * Warning: This file was automatically generated by [hawk], please do not edit.
 *          Thu 25 Jun 19:02:43 CEST 2020
 *
 * R. Carbone (rocco@tecsiel.it)
 * Jun 2020
 *
 * SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * This file was developed as part of the ongoing activities related
 * to the design, implementation and execution of interoperability tests
 * between hacca-based versus AurigaHL7-based applications.
 *
 * In more details I decided to extend AurigaHL7 C++ Library with header files
 * implementing HL7 structures of the version 2.8.1 of the protocol (April 2014)
 * because the version 2.4 distributed with AurigaHL7 is a bit outdated (October 2000).
 *
 * All files in this fork was automatically generated by hacca-based tool [hawk]
 * and strictly follow the syntax and convention originally defined
 * by Auriga HL7 C++ Library just as form of continuity, convenience
 * and respect for their superb work.
 */


#ifndef __DER_O44__281_H__
#define __DER_O44__281_H__

#include "../../common/Util.h"
#include "../segment/AL1.h"
#include "../segment/ARV.h"
#include "../segment/MSH.h"
#include "../segment/NTE.h"
#include "../segment/OBR.h"
#include "../segment/OBX.h"
#include "../segment/PD1.h"
#include "../segment/PID.h"
#include "../segment/PV1.h"
#include "../segment/SFT.h"
#include "../segment/UAC.h"

namespace HL7_281 {

/* Internal structures/groups */
struct DER_O44_DONOR; /* DONOR */
struct DER_O44_DONATION_ORDER; /* DONATION_ORDER */
struct DER_O44_DONOR_REGISTRATION; /* DONOR_REGISTRATION */

/* DONOR */
struct DER_O44_DONOR : public HL7Group {
  DER_O44_DONOR() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    DER_O44_AL1_1,
    DER_O44_ARV_2,
    DER_O44_DER_O44_DONOR_REGISTRATION_3,
    DER_O44_NTE_4,
    DER_O44_OBX_5,
    DER_O44_PD1_6,
    DER_O44_PID_7,
    FIELD_ID_MAX
  };

  const char* className() const { return "DER_O44_DONOR"; }
  DER_O44_DONOR* create() const { return new DER_O44_DONOR(); }

 private:
  /* Initialize object */
  void init() {
    setName("DER_O44.DONOR");
    addObject<AL1>(DER_O44_AL1_1, "AL1.1", HL7::optional, HL7::repetition_on);
    addObject<ARV>(DER_O44_ARV_2, "ARV.2", HL7::optional, HL7::repetition_on);
    addObject<DER_O44_DONOR_REGISTRATION>(DER_O44_DER_O44_DONOR_REGISTRATION_3, "DER_O44_DONOR_REGISTRATION.3", HL7::optional, HL7::repetition_on);
    addObject<NTE>(DER_O44_NTE_4, "NTE.4", HL7::optional, HL7::repetition_on);
    addObject<OBX>(DER_O44_OBX_5, "OBX.5", HL7::optional, HL7::repetition_on);
    addObject<PD1>(DER_O44_PD1_6, "PD1.6", HL7::optional, HL7::repetition_on);
    addObject<PID>(DER_O44_PID_7, "PID.7", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  AL1* getAL1_1(size_t index = 0) {
    return (AL1*)this->getObjectSafe(index, DER_O44_AL1_1);
  }
  ARV* getARV_2(size_t index = 0) {
    return (ARV*)this->getObjectSafe(index, DER_O44_ARV_2);
  }
  DER_O44_DONOR_REGISTRATION* getDER_O44_DONOR_REGISTRATION_3(size_t index = 0) {
    return (DER_O44_DONOR_REGISTRATION*)this->getObjectSafe(index, DER_O44_DER_O44_DONOR_REGISTRATION_3);
  }
  NTE* getNTE_4(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, DER_O44_NTE_4);
  }
  OBX* getOBX_5(size_t index = 0) {
    return (OBX*)this->getObjectSafe(index, DER_O44_OBX_5);
  }
  PD1* getPD1_6(size_t index = 0) {
    return (PD1*)this->getObjectSafe(index, DER_O44_PD1_6);
  }
  PID* getPID_7(size_t index = 0) {
    return (PID*)this->getObjectSafe(index, DER_O44_PID_7);
  }

  /* Checker list */
  bool isAL1_1(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_AL1_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isARV_2(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_ARV_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isDER_O44_DONOR_REGISTRATION_3(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_DER_O44_DONOR_REGISTRATION_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_4(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_NTE_4) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBX_5(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_OBX_5) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPD1_6(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_PD1_6) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPID_7(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_PID_7) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* DER_O44_DONOR */

/* DONATION_ORDER */
struct DER_O44_DONATION_ORDER : public HL7Group {
  DER_O44_DONATION_ORDER() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    DER_O44_NTE_1,
    DER_O44_OBR_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "DER_O44_DONATION_ORDER"; }
  DER_O44_DONATION_ORDER* create() const { return new DER_O44_DONATION_ORDER(); }

 private:
  /* Initialize object */
  void init() {
    setName("DER_O44.DONATION_ORDER");
    addObject<NTE>(DER_O44_NTE_1, "NTE.1", HL7::optional, HL7::repetition_on);
    addObject<OBR>(DER_O44_OBR_2, "OBR.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  NTE* getNTE_1(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, DER_O44_NTE_1);
  }
  OBR* getOBR_2(size_t index = 0) {
    return (OBR*)this->getObjectSafe(index, DER_O44_OBR_2);
  }

  /* Checker list */
  bool isNTE_1(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_NTE_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBR_2(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_OBR_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* DER_O44_DONATION_ORDER */

/* DONOR_REGISTRATION */
struct DER_O44_DONOR_REGISTRATION : public HL7Group {
  DER_O44_DONOR_REGISTRATION() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    DER_O44_NTE_1,
    DER_O44_PV1_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "DER_O44_DONOR_REGISTRATION"; }
  DER_O44_DONOR_REGISTRATION* create() const { return new DER_O44_DONOR_REGISTRATION(); }

 private:
  /* Initialize object */
  void init() {
    setName("DER_O44.DONOR_REGISTRATION");
    addObject<NTE>(DER_O44_NTE_1, "NTE.1", HL7::optional, HL7::repetition_on);
    addObject<PV1>(DER_O44_PV1_2, "PV1.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  NTE* getNTE_1(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, DER_O44_NTE_1);
  }
  PV1* getPV1_2(size_t index = 0) {
    return (PV1*)this->getObjectSafe(index, DER_O44_PV1_2);
  }

  /* Checker list */
  bool isNTE_1(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_NTE_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPV1_2(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_PV1_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* DER_O44_DONOR_REGISTRATION */

/* DER_O44 */
struct DER_O44 : public HL7Message {
  DER_O44() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    DER_O44_MSH_1,
    DER_O44_SFT_2,
    DER_O44_UAC_3,
    DER_O44_OBR_6,
    DER_O44_NTE_7,
    DER_O44_PID_8,
    DER_O44_PD1_9,
    DER_O44_OBX_10,
    DER_O44_NTE_11,
    DER_O44_AL1_12,
    DER_O44_ARV_13,
    DER_O44_PV1_15,
    DER_O44_NTE_16,
    FIELD_ID_MAX
  };

  const char* className() const { return "DER_O44"; }
  DER_O44* create() const { return new DER_O44(); }

 private:
  /* Initialize object */
  void init() {
    setName("DER_O44");
    addObject<MSH>(DER_O44_MSH_1, "MSH.1", HL7::initialized, HL7::repetition_off);
    addObject<SFT>(DER_O44_SFT_2, "SFT.2", HL7::optional, HL7::repetition_on);
    addObject<UAC>(DER_O44_UAC_3, "UAC.3", HL7::optional, HL7::repetition_off);
    addObject<OBR>(DER_O44_OBR_6, "OBR.6", HL7::initialized, HL7::repetition_off);
    addObject<NTE>(DER_O44_NTE_7, "NTE.7", HL7::optional, HL7::repetition_off);
    addObject<PID>(DER_O44_PID_8, "PID.8", HL7::initialized, HL7::repetition_off);
    addObject<PD1>(DER_O44_PD1_9, "PD1.9", HL7::optional, HL7::repetition_off);
    addObject<OBX>(DER_O44_OBX_10, "OBX.10", HL7::optional, HL7::repetition_off);
    addObject<NTE>(DER_O44_NTE_11, "NTE.11", HL7::optional, HL7::repetition_off);
    addObject<AL1>(DER_O44_AL1_12, "AL1.12", HL7::optional, HL7::repetition_off);
    addObject<ARV>(DER_O44_ARV_13, "ARV.13", HL7::optional, HL7::repetition_off);
    addObject<PV1>(DER_O44_PV1_15, "PV1.15", HL7::optional, HL7::repetition_off);
    addObject<NTE>(DER_O44_NTE_16, "NTE.16", HL7::optional, HL7::repetition_off);
  }

 public:
  /* Getters list */
  MSH* getMSH_1(size_t index = 0) {
    return (MSH*)this->getObjectSafe(index, DER_O44_MSH_1);
  }
  SFT* getSFT_2(size_t index = 0) {
    return (SFT*)this->getObjectSafe(index, DER_O44_SFT_2);
  }
  UAC* getUAC_3(size_t index = 0) {
    return (UAC*)this->getObjectSafe(index, DER_O44_UAC_3);
  }
  OBR* getOBR_6(size_t index = 0) {
    return (OBR*)this->getObjectSafe(index, DER_O44_OBR_6);
  }
  NTE* getNTE_7(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, DER_O44_NTE_7);
  }
  PID* getPID_8(size_t index = 0) {
    return (PID*)this->getObjectSafe(index, DER_O44_PID_8);
  }
  PD1* getPD1_9(size_t index = 0) {
    return (PD1*)this->getObjectSafe(index, DER_O44_PD1_9);
  }
  OBX* getOBX_10(size_t index = 0) {
    return (OBX*)this->getObjectSafe(index, DER_O44_OBX_10);
  }
  NTE* getNTE_11(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, DER_O44_NTE_11);
  }
  AL1* getAL1_12(size_t index = 0) {
    return (AL1*)this->getObjectSafe(index, DER_O44_AL1_12);
  }
  ARV* getARV_13(size_t index = 0) {
    return (ARV*)this->getObjectSafe(index, DER_O44_ARV_13);
  }
  PV1* getPV1_15(size_t index = 0) {
    return (PV1*)this->getObjectSafe(index, DER_O44_PV1_15);
  }
  NTE* getNTE_16(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, DER_O44_NTE_16);
  }

  /* Checker list */
  bool isMSH_1(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_MSH_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isSFT_2(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_SFT_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isUAC_3(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_UAC_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBR_6(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_OBR_6) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_7(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_NTE_7) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPID_8(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_PID_8) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPD1_9(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_PD1_9) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBX_10(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_OBX_10) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_11(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_NTE_11) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isAL1_12(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_AL1_12) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isARV_13(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_ARV_13) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPV1_15(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_PV1_15) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_16(size_t index = 0) {
    try {
      return this->getObject(index, DER_O44_NTE_16) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* DER_O44_ */
} /* namespace HL7_281 */
#endif /*  __DER_O44__281_H__ */
