/*
 * hacca - C Toolkit for the HL7 Protocol
 *
 * Warning: This file was automatically generated by [hawk], please do not edit.
 *          Thu 25 Jun 19:02:56 CEST 2020
 *
 * R. Carbone (rocco@tecsiel.it)
 * Jun 2020
 *
 * SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * This file was developed as part of the ongoing activities related
 * to the design, implementation and execution of interoperability tests
 * between hacca-based versus AurigaHL7-based applications.
 *
 * In more details I decided to extend AurigaHL7 C++ Library with header files
 * implementing HL7 structures of the version 2.8.1 of the protocol (April 2014)
 * because the version 2.4 distributed with AurigaHL7 is a bit outdated (October 2000).
 *
 * All files in this fork was automatically generated by hacca-based tool [hawk]
 * and strictly follow the syntax and convention originally defined
 * by Auriga HL7 C++ Library just as form of continuity, convenience
 * and respect for their superb work.
 */


#ifndef __EHC_E01__281_H__
#define __EHC_E01__281_H__

#include "../../common/Util.h"
#include "../segment/ACC.h"
#include "../segment/ADJ.h"
#include "../segment/AUT.h"
#include "../segment/CTD.h"
#include "../segment/DG1.h"
#include "../segment/IN1.h"
#include "../segment/IN2.h"
#include "../segment/IPR.h"
#include "../segment/IVC.h"
#include "../segment/LOC.h"
#include "../segment/MSH.h"
#include "../segment/NTE.h"
#include "../segment/OBX.h"
#include "../segment/PID.h"
#include "../segment/PR1.h"
#include "../segment/PRT.h"
#include "../segment/PSG.h"
#include "../segment/PSL.h"
#include "../segment/PSS.h"
#include "../segment/PV1.h"
#include "../segment/PV2.h"
#include "../segment/PYE.h"
#include "../segment/ROL.h"
#include "../segment/SFT.h"
#include "../segment/UAC.h"

namespace HL7_281 {

/* Internal structures/groups */
struct EHC_E01_PRODUCT_SERVICE_SECTION; /* PRODUCT_SERVICE_SECTION */
struct EHC_E01_PRODUCT_SERVICE_GROUP; /* PRODUCT_SERVICE_GROUP */
struct EHC_E01_PATIENT_INFO; /* PATIENT_INFO */
struct EHC_E01_PRODUCT_SERVICE_LINE_ITEM; /* PRODUCT_SERVICE_LINE_ITEM */
struct EHC_E01_PROCEDURE; /* PROCEDURE */
struct EHC_E01_INSURANCE; /* INSURANCE */
struct EHC_E01_DIAGNOSIS; /* DIAGNOSIS */
struct EHC_E01_INSURANCE; /* INSURANCE */
struct EHC_E01_DIAGNOSIS; /* DIAGNOSIS */
struct EHC_E01_INSURANCE; /* INSURANCE */
struct EHC_E01_DIAGNOSIS; /* DIAGNOSIS */

/* PRODUCT_SERVICE_SECTION */
struct EHC_E01_PRODUCT_SERVICE_SECTION : public HL7Group {
  EHC_E01_PRODUCT_SERVICE_SECTION() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    EHC_E01_EHC_E01_PRODUCT_SERVICE_GROUP_1,
    EHC_E01_PSS_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "EHC_E01_PRODUCT_SERVICE_SECTION"; }
  EHC_E01_PRODUCT_SERVICE_SECTION* create() const { return new EHC_E01_PRODUCT_SERVICE_SECTION(); }

 private:
  /* Initialize object */
  void init() {
    setName("EHC_E01.PRODUCT_SERVICE_SECTION");
    addObject<EHC_E01_PRODUCT_SERVICE_GROUP>(EHC_E01_EHC_E01_PRODUCT_SERVICE_GROUP_1, "EHC_E01_PRODUCT_SERVICE_GROUP.1", HL7::optional, HL7::repetition_on);
    addObject<PSS>(EHC_E01_PSS_2, "PSS.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  EHC_E01_PRODUCT_SERVICE_GROUP* getEHC_E01_PRODUCT_SERVICE_GROUP_1(size_t index = 0) {
    return (EHC_E01_PRODUCT_SERVICE_GROUP*)this->getObjectSafe(index, EHC_E01_EHC_E01_PRODUCT_SERVICE_GROUP_1);
  }
  PSS* getPSS_2(size_t index = 0) {
    return (PSS*)this->getObjectSafe(index, EHC_E01_PSS_2);
  }

  /* Checker list */
  bool isEHC_E01_PRODUCT_SERVICE_GROUP_1(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_EHC_E01_PRODUCT_SERVICE_GROUP_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPSS_2(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PSS_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* EHC_E01_PRODUCT_SERVICE_SECTION */

/* PRODUCT_SERVICE_GROUP */
struct EHC_E01_PRODUCT_SERVICE_GROUP : public HL7Group {
  EHC_E01_PRODUCT_SERVICE_GROUP() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    EHC_E01_EHC_E01_PATIENT_INFO_1,
    EHC_E01_EHC_E01_PROCEDURE_2,
    EHC_E01_EHC_E01_PRODUCT_SERVICE_LINE_ITEM_3,
    EHC_E01_IPR_4,
    EHC_E01_LOC_5,
    EHC_E01_PRT_6,
    EHC_E01_PSG_7,
    EHC_E01_ROL_8,
    FIELD_ID_MAX
  };

  const char* className() const { return "EHC_E01_PRODUCT_SERVICE_GROUP"; }
  EHC_E01_PRODUCT_SERVICE_GROUP* create() const { return new EHC_E01_PRODUCT_SERVICE_GROUP(); }

 private:
  /* Initialize object */
  void init() {
    setName("EHC_E01.PRODUCT_SERVICE_GROUP");
    addObject<EHC_E01_PATIENT_INFO>(EHC_E01_EHC_E01_PATIENT_INFO_1, "EHC_E01_PATIENT_INFO.1", HL7::optional, HL7::repetition_on);
    addObject<EHC_E01_PROCEDURE>(EHC_E01_EHC_E01_PROCEDURE_2, "EHC_E01_PROCEDURE.2", HL7::optional, HL7::repetition_on);
    addObject<EHC_E01_PRODUCT_SERVICE_LINE_ITEM>(EHC_E01_EHC_E01_PRODUCT_SERVICE_LINE_ITEM_3, "EHC_E01_PRODUCT_SERVICE_LINE_ITEM.3", HL7::optional, HL7::repetition_on);
    addObject<IPR>(EHC_E01_IPR_4, "IPR.4", HL7::optional, HL7::repetition_on);
    addObject<LOC>(EHC_E01_LOC_5, "LOC.5", HL7::optional, HL7::repetition_on);
    addObject<PRT>(EHC_E01_PRT_6, "PRT.6", HL7::optional, HL7::repetition_on);
    addObject<PSG>(EHC_E01_PSG_7, "PSG.7", HL7::optional, HL7::repetition_on);
    addObject<ROL>(EHC_E01_ROL_8, "ROL.8", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  EHC_E01_PATIENT_INFO* getEHC_E01_PATIENT_INFO_1(size_t index = 0) {
    return (EHC_E01_PATIENT_INFO*)this->getObjectSafe(index, EHC_E01_EHC_E01_PATIENT_INFO_1);
  }
  EHC_E01_PROCEDURE* getEHC_E01_PROCEDURE_2(size_t index = 0) {
    return (EHC_E01_PROCEDURE*)this->getObjectSafe(index, EHC_E01_EHC_E01_PROCEDURE_2);
  }
  EHC_E01_PRODUCT_SERVICE_LINE_ITEM* getEHC_E01_PRODUCT_SERVICE_LINE_ITEM_3(size_t index = 0) {
    return (EHC_E01_PRODUCT_SERVICE_LINE_ITEM*)this->getObjectSafe(index, EHC_E01_EHC_E01_PRODUCT_SERVICE_LINE_ITEM_3);
  }
  IPR* getIPR_4(size_t index = 0) {
    return (IPR*)this->getObjectSafe(index, EHC_E01_IPR_4);
  }
  LOC* getLOC_5(size_t index = 0) {
    return (LOC*)this->getObjectSafe(index, EHC_E01_LOC_5);
  }
  PRT* getPRT_6(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, EHC_E01_PRT_6);
  }
  PSG* getPSG_7(size_t index = 0) {
    return (PSG*)this->getObjectSafe(index, EHC_E01_PSG_7);
  }
  ROL* getROL_8(size_t index = 0) {
    return (ROL*)this->getObjectSafe(index, EHC_E01_ROL_8);
  }

  /* Checker list */
  bool isEHC_E01_PATIENT_INFO_1(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_EHC_E01_PATIENT_INFO_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isEHC_E01_PROCEDURE_2(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_EHC_E01_PROCEDURE_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isEHC_E01_PRODUCT_SERVICE_LINE_ITEM_3(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_EHC_E01_PRODUCT_SERVICE_LINE_ITEM_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIPR_4(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IPR_4) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isLOC_5(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_LOC_5) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_6(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PRT_6) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPSG_7(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PSG_7) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isROL_8(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_ROL_8) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* EHC_E01_PRODUCT_SERVICE_GROUP */

/* PATIENT_INFO */
struct EHC_E01_PATIENT_INFO : public HL7Group {
  EHC_E01_PATIENT_INFO() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    EHC_E01_ACC_1,
    EHC_E01_EHC_E01_DIAGNOSIS_2,
    EHC_E01_EHC_E01_INSURANCE_3,
    EHC_E01_OBX_4,
    EHC_E01_PID_5,
    EHC_E01_PV1_6,
    EHC_E01_PV2_7,
    FIELD_ID_MAX
  };

  const char* className() const { return "EHC_E01_PATIENT_INFO"; }
  EHC_E01_PATIENT_INFO* create() const { return new EHC_E01_PATIENT_INFO(); }

 private:
  /* Initialize object */
  void init() {
    setName("EHC_E01.PATIENT_INFO");
    addObject<ACC>(EHC_E01_ACC_1, "ACC.1", HL7::optional, HL7::repetition_on);
    addObject<EHC_E01_DIAGNOSIS>(EHC_E01_EHC_E01_DIAGNOSIS_2, "EHC_E01_DIAGNOSIS.2", HL7::optional, HL7::repetition_on);
    addObject<EHC_E01_INSURANCE>(EHC_E01_EHC_E01_INSURANCE_3, "EHC_E01_INSURANCE.3", HL7::optional, HL7::repetition_on);
    addObject<OBX>(EHC_E01_OBX_4, "OBX.4", HL7::optional, HL7::repetition_on);
    addObject<PID>(EHC_E01_PID_5, "PID.5", HL7::optional, HL7::repetition_on);
    addObject<PV1>(EHC_E01_PV1_6, "PV1.6", HL7::optional, HL7::repetition_on);
    addObject<PV2>(EHC_E01_PV2_7, "PV2.7", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  ACC* getACC_1(size_t index = 0) {
    return (ACC*)this->getObjectSafe(index, EHC_E01_ACC_1);
  }
  EHC_E01_DIAGNOSIS* getEHC_E01_DIAGNOSIS_2(size_t index = 0) {
    return (EHC_E01_DIAGNOSIS*)this->getObjectSafe(index, EHC_E01_EHC_E01_DIAGNOSIS_2);
  }
  EHC_E01_INSURANCE* getEHC_E01_INSURANCE_3(size_t index = 0) {
    return (EHC_E01_INSURANCE*)this->getObjectSafe(index, EHC_E01_EHC_E01_INSURANCE_3);
  }
  OBX* getOBX_4(size_t index = 0) {
    return (OBX*)this->getObjectSafe(index, EHC_E01_OBX_4);
  }
  PID* getPID_5(size_t index = 0) {
    return (PID*)this->getObjectSafe(index, EHC_E01_PID_5);
  }
  PV1* getPV1_6(size_t index = 0) {
    return (PV1*)this->getObjectSafe(index, EHC_E01_PV1_6);
  }
  PV2* getPV2_7(size_t index = 0) {
    return (PV2*)this->getObjectSafe(index, EHC_E01_PV2_7);
  }

  /* Checker list */
  bool isACC_1(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_ACC_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isEHC_E01_DIAGNOSIS_2(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_EHC_E01_DIAGNOSIS_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isEHC_E01_INSURANCE_3(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_EHC_E01_INSURANCE_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBX_4(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_OBX_4) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPID_5(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PID_5) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPV1_6(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PV1_6) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPV2_7(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PV2_7) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* EHC_E01_PATIENT_INFO */

/* PRODUCT_SERVICE_LINE_ITEM */
struct EHC_E01_PRODUCT_SERVICE_LINE_ITEM : public HL7Group {
  EHC_E01_PRODUCT_SERVICE_LINE_ITEM() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    EHC_E01_ADJ_1,
    EHC_E01_AUT_2,
    EHC_E01_LOC_3,
    EHC_E01_NTE_4,
    EHC_E01_PRT_5,
    EHC_E01_PSL_6,
    EHC_E01_ROL_7,
    FIELD_ID_MAX
  };

  const char* className() const { return "EHC_E01_PRODUCT_SERVICE_LINE_ITEM"; }
  EHC_E01_PRODUCT_SERVICE_LINE_ITEM* create() const { return new EHC_E01_PRODUCT_SERVICE_LINE_ITEM(); }

 private:
  /* Initialize object */
  void init() {
    setName("EHC_E01.PRODUCT_SERVICE_LINE_ITEM");
    addObject<ADJ>(EHC_E01_ADJ_1, "ADJ.1", HL7::optional, HL7::repetition_on);
    addObject<AUT>(EHC_E01_AUT_2, "AUT.2", HL7::optional, HL7::repetition_on);
    addObject<LOC>(EHC_E01_LOC_3, "LOC.3", HL7::optional, HL7::repetition_on);
    addObject<NTE>(EHC_E01_NTE_4, "NTE.4", HL7::optional, HL7::repetition_on);
    addObject<PRT>(EHC_E01_PRT_5, "PRT.5", HL7::optional, HL7::repetition_on);
    addObject<PSL>(EHC_E01_PSL_6, "PSL.6", HL7::optional, HL7::repetition_on);
    addObject<ROL>(EHC_E01_ROL_7, "ROL.7", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  ADJ* getADJ_1(size_t index = 0) {
    return (ADJ*)this->getObjectSafe(index, EHC_E01_ADJ_1);
  }
  AUT* getAUT_2(size_t index = 0) {
    return (AUT*)this->getObjectSafe(index, EHC_E01_AUT_2);
  }
  LOC* getLOC_3(size_t index = 0) {
    return (LOC*)this->getObjectSafe(index, EHC_E01_LOC_3);
  }
  NTE* getNTE_4(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, EHC_E01_NTE_4);
  }
  PRT* getPRT_5(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, EHC_E01_PRT_5);
  }
  PSL* getPSL_6(size_t index = 0) {
    return (PSL*)this->getObjectSafe(index, EHC_E01_PSL_6);
  }
  ROL* getROL_7(size_t index = 0) {
    return (ROL*)this->getObjectSafe(index, EHC_E01_ROL_7);
  }

  /* Checker list */
  bool isADJ_1(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_ADJ_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isAUT_2(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_AUT_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isLOC_3(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_LOC_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_4(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_NTE_4) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_5(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PRT_5) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPSL_6(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PSL_6) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isROL_7(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_ROL_7) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* EHC_E01_PRODUCT_SERVICE_LINE_ITEM */

/* PROCEDURE */
struct EHC_E01_PROCEDURE : public HL7Group {
  EHC_E01_PROCEDURE() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    EHC_E01_NTE_1,
    EHC_E01_PR1_2,
    EHC_E01_PRT_3,
    EHC_E01_ROL_4,
    FIELD_ID_MAX
  };

  const char* className() const { return "EHC_E01_PROCEDURE"; }
  EHC_E01_PROCEDURE* create() const { return new EHC_E01_PROCEDURE(); }

 private:
  /* Initialize object */
  void init() {
    setName("EHC_E01.PROCEDURE");
    addObject<NTE>(EHC_E01_NTE_1, "NTE.1", HL7::optional, HL7::repetition_on);
    addObject<PR1>(EHC_E01_PR1_2, "PR1.2", HL7::optional, HL7::repetition_on);
    addObject<PRT>(EHC_E01_PRT_3, "PRT.3", HL7::optional, HL7::repetition_on);
    addObject<ROL>(EHC_E01_ROL_4, "ROL.4", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  NTE* getNTE_1(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, EHC_E01_NTE_1);
  }
  PR1* getPR1_2(size_t index = 0) {
    return (PR1*)this->getObjectSafe(index, EHC_E01_PR1_2);
  }
  PRT* getPRT_3(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, EHC_E01_PRT_3);
  }
  ROL* getROL_4(size_t index = 0) {
    return (ROL*)this->getObjectSafe(index, EHC_E01_ROL_4);
  }

  /* Checker list */
  bool isNTE_1(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_NTE_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPR1_2(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PR1_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_3(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PRT_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isROL_4(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_ROL_4) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* EHC_E01_PROCEDURE */

/* INSURANCE */
struct EHC_E01_INSURANCE : public HL7Group {
  EHC_E01_INSURANCE() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    EHC_E01_IN1_1,
    EHC_E01_IN2_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "EHC_E01_INSURANCE"; }
  EHC_E01_INSURANCE* create() const { return new EHC_E01_INSURANCE(); }

 private:
  /* Initialize object */
  void init() {
    setName("EHC_E01.INSURANCE");
    addObject<IN1>(EHC_E01_IN1_1, "IN1.1", HL7::optional, HL7::repetition_on);
    addObject<IN2>(EHC_E01_IN2_2, "IN2.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  IN1* getIN1_1(size_t index = 0) {
    return (IN1*)this->getObjectSafe(index, EHC_E01_IN1_1);
  }
  IN2* getIN2_2(size_t index = 0) {
    return (IN2*)this->getObjectSafe(index, EHC_E01_IN2_2);
  }

  /* Checker list */
  bool isIN1_1(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IN1_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIN2_2(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IN2_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* EHC_E01_INSURANCE */

/* DIAGNOSIS */
struct EHC_E01_DIAGNOSIS : public HL7Group {
  EHC_E01_DIAGNOSIS() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    EHC_E01_DG1_1,
    EHC_E01_NTE_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "EHC_E01_DIAGNOSIS"; }
  EHC_E01_DIAGNOSIS* create() const { return new EHC_E01_DIAGNOSIS(); }

 private:
  /* Initialize object */
  void init() {
    setName("EHC_E01.DIAGNOSIS");
    addObject<DG1>(EHC_E01_DG1_1, "DG1.1", HL7::optional, HL7::repetition_on);
    addObject<NTE>(EHC_E01_NTE_2, "NTE.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  DG1* getDG1_1(size_t index = 0) {
    return (DG1*)this->getObjectSafe(index, EHC_E01_DG1_1);
  }
  NTE* getNTE_2(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, EHC_E01_NTE_2);
  }

  /* Checker list */
  bool isDG1_1(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_DG1_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_2(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_NTE_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* EHC_E01_DIAGNOSIS */

/* EHC_E01 */
struct EHC_E01 : public HL7Message {
  EHC_E01() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    EHC_E01_MSH_1,
    EHC_E01_SFT_2,
    EHC_E01_UAC_3,
    EHC_E01_IVC_4,
    EHC_E01_PYE_5,
    EHC_E01_CTD_6,
    EHC_E01_AUT_7,
    EHC_E01_LOC_8,
    EHC_E01_PRT_9,
    EHC_E01_ROL_10,
    EHC_E01_PSS_12,
    EHC_E01_PSG_35,
    EHC_E01_LOC_36,
    EHC_E01_PRT_37,
    EHC_E01_ROL_38,
    EHC_E01_IPR_42,
    EHC_E01_PID_64,
    EHC_E01_PV1_65,
    EHC_E01_PV2_66,
    EHC_E01_ACC_67,
    EHC_E01_OBX_70,
    EHC_E01_IN1_92,
    EHC_E01_IN2_93,
    EHC_E01_IN1_115,
    EHC_E01_IN2_116,
    EHC_E01_DG1_138,
    EHC_E01_NTE_139,
    EHC_E01_PID_161,
    EHC_E01_PV1_162,
    EHC_E01_PV2_163,
    EHC_E01_ACC_164,
    EHC_E01_OBX_167,
    EHC_E01_PSL_189,
    EHC_E01_NTE_190,
    EHC_E01_ADJ_191,
    EHC_E01_AUT_192,
    EHC_E01_LOC_193,
    EHC_E01_PRT_194,
    EHC_E01_ROL_195,
    EHC_E01_IN1_217,
    EHC_E01_IN2_218,
    EHC_E01_IN1_240,
    EHC_E01_IN2_241,
    EHC_E01_DG1_263,
    EHC_E01_NTE_264,
    EHC_E01_PID_286,
    EHC_E01_PV1_287,
    EHC_E01_PV2_288,
    EHC_E01_ACC_289,
    EHC_E01_OBX_292,
    EHC_E01_PSL_314,
    EHC_E01_NTE_315,
    EHC_E01_ADJ_316,
    EHC_E01_AUT_317,
    EHC_E01_LOC_318,
    EHC_E01_PRT_319,
    EHC_E01_ROL_320,
    EHC_E01_PR1_342,
    EHC_E01_NTE_343,
    EHC_E01_PRT_344,
    EHC_E01_ROL_345,
    EHC_E01_IN1_367,
    EHC_E01_IN2_368,
    EHC_E01_IN1_390,
    EHC_E01_IN2_391,
    EHC_E01_DG1_413,
    EHC_E01_NTE_414,
    FIELD_ID_MAX
  };

  const char* className() const { return "EHC_E01"; }
  EHC_E01* create() const { return new EHC_E01(); }

 private:
  /* Initialize object */
  void init() {
    setName("EHC_E01");
    addObject<MSH>(EHC_E01_MSH_1, "MSH.1", HL7::initialized, HL7::repetition_off);
    addObject<SFT>(EHC_E01_SFT_2, "SFT.2", HL7::optional, HL7::repetition_on);
    addObject<UAC>(EHC_E01_UAC_3, "UAC.3", HL7::optional, HL7::repetition_on);
    addObject<IVC>(EHC_E01_IVC_4, "IVC.4", HL7::initialized, HL7::repetition_off);
    addObject<PYE>(EHC_E01_PYE_5, "PYE.5", HL7::optional, HL7::repetition_off);
    addObject<CTD>(EHC_E01_CTD_6, "CTD.6", HL7::optional, HL7::repetition_on);
    addObject<AUT>(EHC_E01_AUT_7, "AUT.7", HL7::optional, HL7::repetition_off);
    addObject<LOC>(EHC_E01_LOC_8, "LOC.8", HL7::optional, HL7::repetition_on);
    addObject<PRT>(EHC_E01_PRT_9, "PRT.9", HL7::optional, HL7::repetition_on);
    addObject<ROL>(EHC_E01_ROL_10, "ROL.10", HL7::optional, HL7::repetition_on);
    addObject<PSS>(EHC_E01_PSS_12, "PSS.12", HL7::initialized, HL7::repetition_off);
    addObject<PSG>(EHC_E01_PSG_35, "PSG.35", HL7::initialized, HL7::repetition_off);
    addObject<LOC>(EHC_E01_LOC_36, "LOC.36", HL7::optional, HL7::repetition_off);
    addObject<PRT>(EHC_E01_PRT_37, "PRT.37", HL7::optional, HL7::repetition_off);
    addObject<ROL>(EHC_E01_ROL_38, "ROL.38", HL7::optional, HL7::repetition_off);
    addObject<IPR>(EHC_E01_IPR_42, "IPR.42", HL7::optional, HL7::repetition_off);
    addObject<PID>(EHC_E01_PID_64, "PID.64", HL7::initialized, HL7::repetition_off);
    addObject<PV1>(EHC_E01_PV1_65, "PV1.65", HL7::optional, HL7::repetition_off);
    addObject<PV2>(EHC_E01_PV2_66, "PV2.66", HL7::optional, HL7::repetition_off);
    addObject<ACC>(EHC_E01_ACC_67, "ACC.67", HL7::optional, HL7::repetition_off);
    addObject<OBX>(EHC_E01_OBX_70, "OBX.70", HL7::optional, HL7::repetition_off);
    addObject<IN1>(EHC_E01_IN1_92, "IN1.92", HL7::initialized, HL7::repetition_off);
    addObject<IN2>(EHC_E01_IN2_93, "IN2.93", HL7::optional, HL7::repetition_off);
    addObject<IN1>(EHC_E01_IN1_115, "IN1.115", HL7::initialized, HL7::repetition_off);
    addObject<IN2>(EHC_E01_IN2_116, "IN2.116", HL7::optional, HL7::repetition_off);
    addObject<DG1>(EHC_E01_DG1_138, "DG1.138", HL7::initialized, HL7::repetition_off);
    addObject<NTE>(EHC_E01_NTE_139, "NTE.139", HL7::optional, HL7::repetition_off);
    addObject<PID>(EHC_E01_PID_161, "PID.161", HL7::initialized, HL7::repetition_off);
    addObject<PV1>(EHC_E01_PV1_162, "PV1.162", HL7::optional, HL7::repetition_off);
    addObject<PV2>(EHC_E01_PV2_163, "PV2.163", HL7::optional, HL7::repetition_off);
    addObject<ACC>(EHC_E01_ACC_164, "ACC.164", HL7::optional, HL7::repetition_off);
    addObject<OBX>(EHC_E01_OBX_167, "OBX.167", HL7::optional, HL7::repetition_off);
    addObject<PSL>(EHC_E01_PSL_189, "PSL.189", HL7::initialized, HL7::repetition_off);
    addObject<NTE>(EHC_E01_NTE_190, "NTE.190", HL7::optional, HL7::repetition_off);
    addObject<ADJ>(EHC_E01_ADJ_191, "ADJ.191", HL7::optional, HL7::repetition_off);
    addObject<AUT>(EHC_E01_AUT_192, "AUT.192", HL7::optional, HL7::repetition_off);
    addObject<LOC>(EHC_E01_LOC_193, "LOC.193", HL7::optional, HL7::repetition_off);
    addObject<PRT>(EHC_E01_PRT_194, "PRT.194", HL7::optional, HL7::repetition_off);
    addObject<ROL>(EHC_E01_ROL_195, "ROL.195", HL7::optional, HL7::repetition_off);
    addObject<IN1>(EHC_E01_IN1_217, "IN1.217", HL7::initialized, HL7::repetition_off);
    addObject<IN2>(EHC_E01_IN2_218, "IN2.218", HL7::optional, HL7::repetition_off);
    addObject<IN1>(EHC_E01_IN1_240, "IN1.240", HL7::initialized, HL7::repetition_off);
    addObject<IN2>(EHC_E01_IN2_241, "IN2.241", HL7::optional, HL7::repetition_off);
    addObject<DG1>(EHC_E01_DG1_263, "DG1.263", HL7::initialized, HL7::repetition_off);
    addObject<NTE>(EHC_E01_NTE_264, "NTE.264", HL7::optional, HL7::repetition_off);
    addObject<PID>(EHC_E01_PID_286, "PID.286", HL7::initialized, HL7::repetition_off);
    addObject<PV1>(EHC_E01_PV1_287, "PV1.287", HL7::optional, HL7::repetition_off);
    addObject<PV2>(EHC_E01_PV2_288, "PV2.288", HL7::optional, HL7::repetition_off);
    addObject<ACC>(EHC_E01_ACC_289, "ACC.289", HL7::optional, HL7::repetition_off);
    addObject<OBX>(EHC_E01_OBX_292, "OBX.292", HL7::optional, HL7::repetition_off);
    addObject<PSL>(EHC_E01_PSL_314, "PSL.314", HL7::initialized, HL7::repetition_off);
    addObject<NTE>(EHC_E01_NTE_315, "NTE.315", HL7::optional, HL7::repetition_off);
    addObject<ADJ>(EHC_E01_ADJ_316, "ADJ.316", HL7::optional, HL7::repetition_off);
    addObject<AUT>(EHC_E01_AUT_317, "AUT.317", HL7::optional, HL7::repetition_off);
    addObject<LOC>(EHC_E01_LOC_318, "LOC.318", HL7::optional, HL7::repetition_off);
    addObject<PRT>(EHC_E01_PRT_319, "PRT.319", HL7::optional, HL7::repetition_off);
    addObject<ROL>(EHC_E01_ROL_320, "ROL.320", HL7::optional, HL7::repetition_off);
    addObject<PR1>(EHC_E01_PR1_342, "PR1.342", HL7::initialized, HL7::repetition_off);
    addObject<NTE>(EHC_E01_NTE_343, "NTE.343", HL7::optional, HL7::repetition_off);
    addObject<PRT>(EHC_E01_PRT_344, "PRT.344", HL7::optional, HL7::repetition_off);
    addObject<ROL>(EHC_E01_ROL_345, "ROL.345", HL7::optional, HL7::repetition_off);
    addObject<IN1>(EHC_E01_IN1_367, "IN1.367", HL7::initialized, HL7::repetition_off);
    addObject<IN2>(EHC_E01_IN2_368, "IN2.368", HL7::optional, HL7::repetition_off);
    addObject<IN1>(EHC_E01_IN1_390, "IN1.390", HL7::initialized, HL7::repetition_off);
    addObject<IN2>(EHC_E01_IN2_391, "IN2.391", HL7::optional, HL7::repetition_off);
    addObject<DG1>(EHC_E01_DG1_413, "DG1.413", HL7::initialized, HL7::repetition_off);
    addObject<NTE>(EHC_E01_NTE_414, "NTE.414", HL7::optional, HL7::repetition_off);
  }

 public:
  /* Getters list */
  MSH* getMSH_1(size_t index = 0) {
    return (MSH*)this->getObjectSafe(index, EHC_E01_MSH_1);
  }
  SFT* getSFT_2(size_t index = 0) {
    return (SFT*)this->getObjectSafe(index, EHC_E01_SFT_2);
  }
  UAC* getUAC_3(size_t index = 0) {
    return (UAC*)this->getObjectSafe(index, EHC_E01_UAC_3);
  }
  IVC* getIVC_4(size_t index = 0) {
    return (IVC*)this->getObjectSafe(index, EHC_E01_IVC_4);
  }
  PYE* getPYE_5(size_t index = 0) {
    return (PYE*)this->getObjectSafe(index, EHC_E01_PYE_5);
  }
  CTD* getCTD_6(size_t index = 0) {
    return (CTD*)this->getObjectSafe(index, EHC_E01_CTD_6);
  }
  AUT* getAUT_7(size_t index = 0) {
    return (AUT*)this->getObjectSafe(index, EHC_E01_AUT_7);
  }
  LOC* getLOC_8(size_t index = 0) {
    return (LOC*)this->getObjectSafe(index, EHC_E01_LOC_8);
  }
  PRT* getPRT_9(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, EHC_E01_PRT_9);
  }
  ROL* getROL_10(size_t index = 0) {
    return (ROL*)this->getObjectSafe(index, EHC_E01_ROL_10);
  }
  PSS* getPSS_12(size_t index = 0) {
    return (PSS*)this->getObjectSafe(index, EHC_E01_PSS_12);
  }
  PSG* getPSG_35(size_t index = 0) {
    return (PSG*)this->getObjectSafe(index, EHC_E01_PSG_35);
  }
  LOC* getLOC_36(size_t index = 0) {
    return (LOC*)this->getObjectSafe(index, EHC_E01_LOC_36);
  }
  PRT* getPRT_37(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, EHC_E01_PRT_37);
  }
  ROL* getROL_38(size_t index = 0) {
    return (ROL*)this->getObjectSafe(index, EHC_E01_ROL_38);
  }
  IPR* getIPR_42(size_t index = 0) {
    return (IPR*)this->getObjectSafe(index, EHC_E01_IPR_42);
  }
  PID* getPID_64(size_t index = 0) {
    return (PID*)this->getObjectSafe(index, EHC_E01_PID_64);
  }
  PV1* getPV1_65(size_t index = 0) {
    return (PV1*)this->getObjectSafe(index, EHC_E01_PV1_65);
  }
  PV2* getPV2_66(size_t index = 0) {
    return (PV2*)this->getObjectSafe(index, EHC_E01_PV2_66);
  }
  ACC* getACC_67(size_t index = 0) {
    return (ACC*)this->getObjectSafe(index, EHC_E01_ACC_67);
  }
  OBX* getOBX_70(size_t index = 0) {
    return (OBX*)this->getObjectSafe(index, EHC_E01_OBX_70);
  }
  IN1* getIN1_92(size_t index = 0) {
    return (IN1*)this->getObjectSafe(index, EHC_E01_IN1_92);
  }
  IN2* getIN2_93(size_t index = 0) {
    return (IN2*)this->getObjectSafe(index, EHC_E01_IN2_93);
  }
  IN1* getIN1_115(size_t index = 0) {
    return (IN1*)this->getObjectSafe(index, EHC_E01_IN1_115);
  }
  IN2* getIN2_116(size_t index = 0) {
    return (IN2*)this->getObjectSafe(index, EHC_E01_IN2_116);
  }
  DG1* getDG1_138(size_t index = 0) {
    return (DG1*)this->getObjectSafe(index, EHC_E01_DG1_138);
  }
  NTE* getNTE_139(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, EHC_E01_NTE_139);
  }
  PID* getPID_161(size_t index = 0) {
    return (PID*)this->getObjectSafe(index, EHC_E01_PID_161);
  }
  PV1* getPV1_162(size_t index = 0) {
    return (PV1*)this->getObjectSafe(index, EHC_E01_PV1_162);
  }
  PV2* getPV2_163(size_t index = 0) {
    return (PV2*)this->getObjectSafe(index, EHC_E01_PV2_163);
  }
  ACC* getACC_164(size_t index = 0) {
    return (ACC*)this->getObjectSafe(index, EHC_E01_ACC_164);
  }
  OBX* getOBX_167(size_t index = 0) {
    return (OBX*)this->getObjectSafe(index, EHC_E01_OBX_167);
  }
  PSL* getPSL_189(size_t index = 0) {
    return (PSL*)this->getObjectSafe(index, EHC_E01_PSL_189);
  }
  NTE* getNTE_190(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, EHC_E01_NTE_190);
  }
  ADJ* getADJ_191(size_t index = 0) {
    return (ADJ*)this->getObjectSafe(index, EHC_E01_ADJ_191);
  }
  AUT* getAUT_192(size_t index = 0) {
    return (AUT*)this->getObjectSafe(index, EHC_E01_AUT_192);
  }
  LOC* getLOC_193(size_t index = 0) {
    return (LOC*)this->getObjectSafe(index, EHC_E01_LOC_193);
  }
  PRT* getPRT_194(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, EHC_E01_PRT_194);
  }
  ROL* getROL_195(size_t index = 0) {
    return (ROL*)this->getObjectSafe(index, EHC_E01_ROL_195);
  }
  IN1* getIN1_217(size_t index = 0) {
    return (IN1*)this->getObjectSafe(index, EHC_E01_IN1_217);
  }
  IN2* getIN2_218(size_t index = 0) {
    return (IN2*)this->getObjectSafe(index, EHC_E01_IN2_218);
  }
  IN1* getIN1_240(size_t index = 0) {
    return (IN1*)this->getObjectSafe(index, EHC_E01_IN1_240);
  }
  IN2* getIN2_241(size_t index = 0) {
    return (IN2*)this->getObjectSafe(index, EHC_E01_IN2_241);
  }
  DG1* getDG1_263(size_t index = 0) {
    return (DG1*)this->getObjectSafe(index, EHC_E01_DG1_263);
  }
  NTE* getNTE_264(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, EHC_E01_NTE_264);
  }
  PID* getPID_286(size_t index = 0) {
    return (PID*)this->getObjectSafe(index, EHC_E01_PID_286);
  }
  PV1* getPV1_287(size_t index = 0) {
    return (PV1*)this->getObjectSafe(index, EHC_E01_PV1_287);
  }
  PV2* getPV2_288(size_t index = 0) {
    return (PV2*)this->getObjectSafe(index, EHC_E01_PV2_288);
  }
  ACC* getACC_289(size_t index = 0) {
    return (ACC*)this->getObjectSafe(index, EHC_E01_ACC_289);
  }
  OBX* getOBX_292(size_t index = 0) {
    return (OBX*)this->getObjectSafe(index, EHC_E01_OBX_292);
  }
  PSL* getPSL_314(size_t index = 0) {
    return (PSL*)this->getObjectSafe(index, EHC_E01_PSL_314);
  }
  NTE* getNTE_315(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, EHC_E01_NTE_315);
  }
  ADJ* getADJ_316(size_t index = 0) {
    return (ADJ*)this->getObjectSafe(index, EHC_E01_ADJ_316);
  }
  AUT* getAUT_317(size_t index = 0) {
    return (AUT*)this->getObjectSafe(index, EHC_E01_AUT_317);
  }
  LOC* getLOC_318(size_t index = 0) {
    return (LOC*)this->getObjectSafe(index, EHC_E01_LOC_318);
  }
  PRT* getPRT_319(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, EHC_E01_PRT_319);
  }
  ROL* getROL_320(size_t index = 0) {
    return (ROL*)this->getObjectSafe(index, EHC_E01_ROL_320);
  }
  PR1* getPR1_342(size_t index = 0) {
    return (PR1*)this->getObjectSafe(index, EHC_E01_PR1_342);
  }
  NTE* getNTE_343(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, EHC_E01_NTE_343);
  }
  PRT* getPRT_344(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, EHC_E01_PRT_344);
  }
  ROL* getROL_345(size_t index = 0) {
    return (ROL*)this->getObjectSafe(index, EHC_E01_ROL_345);
  }
  IN1* getIN1_367(size_t index = 0) {
    return (IN1*)this->getObjectSafe(index, EHC_E01_IN1_367);
  }
  IN2* getIN2_368(size_t index = 0) {
    return (IN2*)this->getObjectSafe(index, EHC_E01_IN2_368);
  }
  IN1* getIN1_390(size_t index = 0) {
    return (IN1*)this->getObjectSafe(index, EHC_E01_IN1_390);
  }
  IN2* getIN2_391(size_t index = 0) {
    return (IN2*)this->getObjectSafe(index, EHC_E01_IN2_391);
  }
  DG1* getDG1_413(size_t index = 0) {
    return (DG1*)this->getObjectSafe(index, EHC_E01_DG1_413);
  }
  NTE* getNTE_414(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, EHC_E01_NTE_414);
  }

  /* Checker list */
  bool isMSH_1(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_MSH_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isSFT_2(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_SFT_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isUAC_3(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_UAC_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIVC_4(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IVC_4) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPYE_5(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PYE_5) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isCTD_6(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_CTD_6) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isAUT_7(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_AUT_7) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isLOC_8(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_LOC_8) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_9(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PRT_9) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isROL_10(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_ROL_10) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPSS_12(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PSS_12) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPSG_35(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PSG_35) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isLOC_36(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_LOC_36) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_37(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PRT_37) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isROL_38(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_ROL_38) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIPR_42(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IPR_42) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPID_64(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PID_64) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPV1_65(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PV1_65) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPV2_66(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PV2_66) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isACC_67(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_ACC_67) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBX_70(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_OBX_70) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIN1_92(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IN1_92) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIN2_93(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IN2_93) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIN1_115(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IN1_115) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIN2_116(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IN2_116) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isDG1_138(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_DG1_138) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_139(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_NTE_139) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPID_161(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PID_161) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPV1_162(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PV1_162) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPV2_163(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PV2_163) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isACC_164(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_ACC_164) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBX_167(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_OBX_167) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPSL_189(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PSL_189) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_190(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_NTE_190) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isADJ_191(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_ADJ_191) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isAUT_192(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_AUT_192) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isLOC_193(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_LOC_193) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_194(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PRT_194) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isROL_195(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_ROL_195) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIN1_217(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IN1_217) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIN2_218(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IN2_218) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIN1_240(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IN1_240) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIN2_241(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IN2_241) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isDG1_263(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_DG1_263) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_264(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_NTE_264) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPID_286(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PID_286) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPV1_287(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PV1_287) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPV2_288(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PV2_288) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isACC_289(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_ACC_289) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBX_292(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_OBX_292) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPSL_314(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PSL_314) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_315(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_NTE_315) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isADJ_316(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_ADJ_316) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isAUT_317(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_AUT_317) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isLOC_318(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_LOC_318) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_319(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PRT_319) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isROL_320(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_ROL_320) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPR1_342(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PR1_342) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_343(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_NTE_343) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_344(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_PRT_344) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isROL_345(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_ROL_345) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIN1_367(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IN1_367) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIN2_368(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IN2_368) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIN1_390(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IN1_390) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIN2_391(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_IN2_391) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isDG1_413(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_DG1_413) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_414(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E01_NTE_414) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* EHC_E01_ */
} /* namespace HL7_281 */
#endif /*  __EHC_E01__281_H__ */
