/*
 * hacca - C Toolkit for the HL7 Protocol
 *
 * Warning: This file was automatically generated by [hawk], please do not edit.
 *          Thu 25 Jun 19:03:20 CEST 2020
 *
 * R. Carbone (rocco@tecsiel.it)
 * Jun 2020
 *
 * SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * This file was developed as part of the ongoing activities related
 * to the design, implementation and execution of interoperability tests
 * between hacca-based versus AurigaHL7-based applications.
 *
 * In more details I decided to extend AurigaHL7 C++ Library with header files
 * implementing HL7 structures of the version 2.8.1 of the protocol (April 2014)
 * because the version 2.4 distributed with AurigaHL7 is a bit outdated (October 2000).
 *
 * All files in this fork was automatically generated by hacca-based tool [hawk]
 * and strictly follow the syntax and convention originally defined
 * by Auriga HL7 C++ Library just as form of continuity, convenience
 * and respect for their superb work.
 */


#ifndef __EHC_E15__281_H__
#define __EHC_E15__281_H__

#include "../../common/Util.h"
#include "../segment/ADJ.h"
#include "../segment/IPR.h"
#include "../segment/IVC.h"
#include "../segment/MSH.h"
#include "../segment/PMT.h"
#include "../segment/PRT.h"
#include "../segment/PSG.h"
#include "../segment/PSL.h"
#include "../segment/PSS.h"
#include "../segment/PYE.h"
#include "../segment/ROL.h"
#include "../segment/SFT.h"
#include "../segment/UAC.h"

namespace HL7_281 {

/* Internal structures/groups */
struct EHC_E15_PAYMENT_REMITTANCE_DETAIL_INFO; /* PAYMENT_REMITTANCE_DETAIL_INFO */
struct EHC_E15_ADJUSTMENT_PAYEE; /* ADJUSTMENT_PAYEE */
struct EHC_E15_PRODUCT_SERVICE_SECTION; /* PRODUCT_SERVICE_SECTION */
struct EHC_E15_PRODUCT_SERVICE_GROUP; /* PRODUCT_SERVICE_GROUP */
struct EHC_E15_PSL_ITEM_INFO; /* PSL_ITEM_INFO */

/* PAYMENT_REMITTANCE_DETAIL_INFO */
struct EHC_E15_PAYMENT_REMITTANCE_DETAIL_INFO : public HL7Group {
  EHC_E15_PAYMENT_REMITTANCE_DETAIL_INFO() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    EHC_E15_EHC_E15_PRODUCT_SERVICE_SECTION_1,
    EHC_E15_IPR_2,
    EHC_E15_IVC_3,
    FIELD_ID_MAX
  };

  const char* className() const { return "EHC_E15_PAYMENT_REMITTANCE_DETAIL_INFO"; }
  EHC_E15_PAYMENT_REMITTANCE_DETAIL_INFO* create() const { return new EHC_E15_PAYMENT_REMITTANCE_DETAIL_INFO(); }

 private:
  /* Initialize object */
  void init() {
    setName("EHC_E15.PAYMENT_REMITTANCE_DETAIL_INFO");
    addObject<EHC_E15_PRODUCT_SERVICE_SECTION>(EHC_E15_EHC_E15_PRODUCT_SERVICE_SECTION_1, "EHC_E15_PRODUCT_SERVICE_SECTION.1", HL7::optional, HL7::repetition_on);
    addObject<IPR>(EHC_E15_IPR_2, "IPR.2", HL7::optional, HL7::repetition_on);
    addObject<IVC>(EHC_E15_IVC_3, "IVC.3", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  EHC_E15_PRODUCT_SERVICE_SECTION* getEHC_E15_PRODUCT_SERVICE_SECTION_1(size_t index = 0) {
    return (EHC_E15_PRODUCT_SERVICE_SECTION*)this->getObjectSafe(index, EHC_E15_EHC_E15_PRODUCT_SERVICE_SECTION_1);
  }
  IPR* getIPR_2(size_t index = 0) {
    return (IPR*)this->getObjectSafe(index, EHC_E15_IPR_2);
  }
  IVC* getIVC_3(size_t index = 0) {
    return (IVC*)this->getObjectSafe(index, EHC_E15_IVC_3);
  }

  /* Checker list */
  bool isEHC_E15_PRODUCT_SERVICE_SECTION_1(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_EHC_E15_PRODUCT_SERVICE_SECTION_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIPR_2(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_IPR_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIVC_3(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_IVC_3) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* EHC_E15_PAYMENT_REMITTANCE_DETAIL_INFO */

/* ADJUSTMENT_PAYEE */
struct EHC_E15_ADJUSTMENT_PAYEE : public HL7Group {
  EHC_E15_ADJUSTMENT_PAYEE() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    EHC_E15_ADJ_1,
    EHC_E15_PRT_2,
    EHC_E15_ROL_3,
    FIELD_ID_MAX
  };

  const char* className() const { return "EHC_E15_ADJUSTMENT_PAYEE"; }
  EHC_E15_ADJUSTMENT_PAYEE* create() const { return new EHC_E15_ADJUSTMENT_PAYEE(); }

 private:
  /* Initialize object */
  void init() {
    setName("EHC_E15.ADJUSTMENT_PAYEE");
    addObject<ADJ>(EHC_E15_ADJ_1, "ADJ.1", HL7::optional, HL7::repetition_on);
    addObject<PRT>(EHC_E15_PRT_2, "PRT.2", HL7::optional, HL7::repetition_on);
    addObject<ROL>(EHC_E15_ROL_3, "ROL.3", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  ADJ* getADJ_1(size_t index = 0) {
    return (ADJ*)this->getObjectSafe(index, EHC_E15_ADJ_1);
  }
  PRT* getPRT_2(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, EHC_E15_PRT_2);
  }
  ROL* getROL_3(size_t index = 0) {
    return (ROL*)this->getObjectSafe(index, EHC_E15_ROL_3);
  }

  /* Checker list */
  bool isADJ_1(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_ADJ_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_2(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_PRT_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isROL_3(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_ROL_3) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* EHC_E15_ADJUSTMENT_PAYEE */

/* PRODUCT_SERVICE_SECTION */
struct EHC_E15_PRODUCT_SERVICE_SECTION : public HL7Group {
  EHC_E15_PRODUCT_SERVICE_SECTION() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    EHC_E15_EHC_E15_PRODUCT_SERVICE_GROUP_1,
    EHC_E15_PSS_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "EHC_E15_PRODUCT_SERVICE_SECTION"; }
  EHC_E15_PRODUCT_SERVICE_SECTION* create() const { return new EHC_E15_PRODUCT_SERVICE_SECTION(); }

 private:
  /* Initialize object */
  void init() {
    setName("EHC_E15.PRODUCT_SERVICE_SECTION");
    addObject<EHC_E15_PRODUCT_SERVICE_GROUP>(EHC_E15_EHC_E15_PRODUCT_SERVICE_GROUP_1, "EHC_E15_PRODUCT_SERVICE_GROUP.1", HL7::optional, HL7::repetition_on);
    addObject<PSS>(EHC_E15_PSS_2, "PSS.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  EHC_E15_PRODUCT_SERVICE_GROUP* getEHC_E15_PRODUCT_SERVICE_GROUP_1(size_t index = 0) {
    return (EHC_E15_PRODUCT_SERVICE_GROUP*)this->getObjectSafe(index, EHC_E15_EHC_E15_PRODUCT_SERVICE_GROUP_1);
  }
  PSS* getPSS_2(size_t index = 0) {
    return (PSS*)this->getObjectSafe(index, EHC_E15_PSS_2);
  }

  /* Checker list */
  bool isEHC_E15_PRODUCT_SERVICE_GROUP_1(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_EHC_E15_PRODUCT_SERVICE_GROUP_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPSS_2(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_PSS_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* EHC_E15_PRODUCT_SERVICE_SECTION */

/* PRODUCT_SERVICE_GROUP */
struct EHC_E15_PRODUCT_SERVICE_GROUP : public HL7Group {
  EHC_E15_PRODUCT_SERVICE_GROUP() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    EHC_E15_EHC_E15_PSL_ITEM_INFO_1,
    EHC_E15_PSG_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "EHC_E15_PRODUCT_SERVICE_GROUP"; }
  EHC_E15_PRODUCT_SERVICE_GROUP* create() const { return new EHC_E15_PRODUCT_SERVICE_GROUP(); }

 private:
  /* Initialize object */
  void init() {
    setName("EHC_E15.PRODUCT_SERVICE_GROUP");
    addObject<EHC_E15_PSL_ITEM_INFO>(EHC_E15_EHC_E15_PSL_ITEM_INFO_1, "EHC_E15_PSL_ITEM_INFO.1", HL7::optional, HL7::repetition_on);
    addObject<PSG>(EHC_E15_PSG_2, "PSG.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  EHC_E15_PSL_ITEM_INFO* getEHC_E15_PSL_ITEM_INFO_1(size_t index = 0) {
    return (EHC_E15_PSL_ITEM_INFO*)this->getObjectSafe(index, EHC_E15_EHC_E15_PSL_ITEM_INFO_1);
  }
  PSG* getPSG_2(size_t index = 0) {
    return (PSG*)this->getObjectSafe(index, EHC_E15_PSG_2);
  }

  /* Checker list */
  bool isEHC_E15_PSL_ITEM_INFO_1(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_EHC_E15_PSL_ITEM_INFO_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPSG_2(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_PSG_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* EHC_E15_PRODUCT_SERVICE_GROUP */

/* PSL_ITEM_INFO */
struct EHC_E15_PSL_ITEM_INFO : public HL7Group {
  EHC_E15_PSL_ITEM_INFO() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    EHC_E15_ADJ_1,
    EHC_E15_PSL_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "EHC_E15_PSL_ITEM_INFO"; }
  EHC_E15_PSL_ITEM_INFO* create() const { return new EHC_E15_PSL_ITEM_INFO(); }

 private:
  /* Initialize object */
  void init() {
    setName("EHC_E15.PSL_ITEM_INFO");
    addObject<ADJ>(EHC_E15_ADJ_1, "ADJ.1", HL7::optional, HL7::repetition_on);
    addObject<PSL>(EHC_E15_PSL_2, "PSL.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  ADJ* getADJ_1(size_t index = 0) {
    return (ADJ*)this->getObjectSafe(index, EHC_E15_ADJ_1);
  }
  PSL* getPSL_2(size_t index = 0) {
    return (PSL*)this->getObjectSafe(index, EHC_E15_PSL_2);
  }

  /* Checker list */
  bool isADJ_1(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_ADJ_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPSL_2(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_PSL_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* EHC_E15_PSL_ITEM_INFO */

/* EHC_E15 */
struct EHC_E15 : public HL7Message {
  EHC_E15() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    EHC_E15_MSH_1,
    EHC_E15_SFT_2,
    EHC_E15_UAC_3,
    EHC_E15_PMT_4,
    EHC_E15_PYE_5,
    EHC_E15_ADJ_8,
    EHC_E15_PRT_9,
    EHC_E15_ROL_10,
    EHC_E15_IPR_11,
    EHC_E15_IVC_12,
    EHC_E15_PSS_14,
    EHC_E15_PSG_16,
    EHC_E15_PSL_18,
    EHC_E15_ADJ_19,
    FIELD_ID_MAX
  };

  const char* className() const { return "EHC_E15"; }
  EHC_E15* create() const { return new EHC_E15(); }

 private:
  /* Initialize object */
  void init() {
    setName("EHC_E15");
    addObject<MSH>(EHC_E15_MSH_1, "MSH.1", HL7::initialized, HL7::repetition_off);
    addObject<SFT>(EHC_E15_SFT_2, "SFT.2", HL7::optional, HL7::repetition_on);
    addObject<UAC>(EHC_E15_UAC_3, "UAC.3", HL7::optional, HL7::repetition_on);
    addObject<PMT>(EHC_E15_PMT_4, "PMT.4", HL7::initialized, HL7::repetition_off);
    addObject<PYE>(EHC_E15_PYE_5, "PYE.5", HL7::initialized, HL7::repetition_off);
    addObject<ADJ>(EHC_E15_ADJ_8, "ADJ.8", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(EHC_E15_PRT_9, "PRT.9", HL7::optional, HL7::repetition_off);
    addObject<ROL>(EHC_E15_ROL_10, "ROL.10", HL7::optional, HL7::repetition_off);
    addObject<IPR>(EHC_E15_IPR_11, "IPR.11", HL7::initialized, HL7::repetition_off);
    addObject<IVC>(EHC_E15_IVC_12, "IVC.12", HL7::initialized, HL7::repetition_off);
    addObject<PSS>(EHC_E15_PSS_14, "PSS.14", HL7::initialized, HL7::repetition_off);
    addObject<PSG>(EHC_E15_PSG_16, "PSG.16", HL7::initialized, HL7::repetition_off);
    addObject<PSL>(EHC_E15_PSL_18, "PSL.18", HL7::initialized, HL7::repetition_off);
    addObject<ADJ>(EHC_E15_ADJ_19, "ADJ.19", HL7::optional, HL7::repetition_off);
  }

 public:
  /* Getters list */
  MSH* getMSH_1(size_t index = 0) {
    return (MSH*)this->getObjectSafe(index, EHC_E15_MSH_1);
  }
  SFT* getSFT_2(size_t index = 0) {
    return (SFT*)this->getObjectSafe(index, EHC_E15_SFT_2);
  }
  UAC* getUAC_3(size_t index = 0) {
    return (UAC*)this->getObjectSafe(index, EHC_E15_UAC_3);
  }
  PMT* getPMT_4(size_t index = 0) {
    return (PMT*)this->getObjectSafe(index, EHC_E15_PMT_4);
  }
  PYE* getPYE_5(size_t index = 0) {
    return (PYE*)this->getObjectSafe(index, EHC_E15_PYE_5);
  }
  ADJ* getADJ_8(size_t index = 0) {
    return (ADJ*)this->getObjectSafe(index, EHC_E15_ADJ_8);
  }
  PRT* getPRT_9(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, EHC_E15_PRT_9);
  }
  ROL* getROL_10(size_t index = 0) {
    return (ROL*)this->getObjectSafe(index, EHC_E15_ROL_10);
  }
  IPR* getIPR_11(size_t index = 0) {
    return (IPR*)this->getObjectSafe(index, EHC_E15_IPR_11);
  }
  IVC* getIVC_12(size_t index = 0) {
    return (IVC*)this->getObjectSafe(index, EHC_E15_IVC_12);
  }
  PSS* getPSS_14(size_t index = 0) {
    return (PSS*)this->getObjectSafe(index, EHC_E15_PSS_14);
  }
  PSG* getPSG_16(size_t index = 0) {
    return (PSG*)this->getObjectSafe(index, EHC_E15_PSG_16);
  }
  PSL* getPSL_18(size_t index = 0) {
    return (PSL*)this->getObjectSafe(index, EHC_E15_PSL_18);
  }
  ADJ* getADJ_19(size_t index = 0) {
    return (ADJ*)this->getObjectSafe(index, EHC_E15_ADJ_19);
  }

  /* Checker list */
  bool isMSH_1(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_MSH_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isSFT_2(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_SFT_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isUAC_3(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_UAC_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPMT_4(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_PMT_4) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPYE_5(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_PYE_5) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isADJ_8(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_ADJ_8) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_9(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_PRT_9) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isROL_10(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_ROL_10) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIPR_11(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_IPR_11) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isIVC_12(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_IVC_12) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPSS_14(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_PSS_14) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPSG_16(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_PSG_16) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPSL_18(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_PSL_18) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isADJ_19(size_t index = 0) {
    try {
      return this->getObject(index, EHC_E15_ADJ_19) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* EHC_E15_ */
} /* namespace HL7_281 */
#endif /*  __EHC_E15__281_H__ */
