/*
 * hacca - C Toolkit for the HL7 Protocol
 *
 * Warning: This file was automatically generated by [hawk], please do not edit.
 *          Thu 25 Jun 19:05:08 CEST 2020
 *
 * R. Carbone (rocco@tecsiel.it)
 * Jun 2020
 *
 * SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * This file was developed as part of the ongoing activities related
 * to the design, implementation and execution of interoperability tests
 * between hacca-based versus AurigaHL7-based applications.
 *
 * In more details I decided to extend AurigaHL7 C++ Library with header files
 * implementing HL7 structures of the version 2.8.1 of the protocol (April 2014)
 * because the version 2.4 distributed with AurigaHL7 is a bit outdated (October 2000).
 *
 * All files in this fork was automatically generated by hacca-based tool [hawk]
 * and strictly follow the syntax and convention originally defined
 * by Auriga HL7 C++ Library just as form of continuity, convenience
 * and respect for their superb work.
 */


#ifndef __ORL_O41__281_H__
#define __ORL_O41__281_H__

#include "../../common/Util.h"
#include "../segment/ERR.h"
#include "../segment/MSA.h"
#include "../segment/MSH.h"
#include "../segment/NTE.h"
#include "../segment/OBR.h"
#include "../segment/ORC.h"
#include "../segment/PID.h"
#include "../segment/PRT.h"
#include "../segment/SAC.h"
#include "../segment/SFT.h"
#include "../segment/SPM.h"
#include "../segment/TQ1.h"
#include "../segment/TQ2.h"
#include "../segment/UAC.h"

namespace HL7_281 {

/* Internal structures/groups */
struct ORL_O41_RESPONSE; /* RESPONSE */
struct ORL_O41_PATIENT; /* PATIENT */
struct ORL_O41_ORDER; /* ORDER */
struct ORL_O41_TIMING; /* TIMING */
struct ORL_O41_OBSERVATION_REQUEST; /* OBSERVATION_REQUEST */
struct ORL_O41_SPECIMEN; /* SPECIMEN */

/* RESPONSE */
struct ORL_O41_RESPONSE : public HL7Group {
  ORL_O41_RESPONSE() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    ORL_O41_ORL_O41_ORDER_1,
    ORL_O41_ORL_O41_PATIENT_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "ORL_O41_RESPONSE"; }
  ORL_O41_RESPONSE* create() const { return new ORL_O41_RESPONSE(); }

 private:
  /* Initialize object */
  void init() {
    setName("ORL_O41.RESPONSE");
    addObject<ORL_O41_ORDER>(ORL_O41_ORL_O41_ORDER_1, "ORL_O41_ORDER.1", HL7::optional, HL7::repetition_on);
    addObject<ORL_O41_PATIENT>(ORL_O41_ORL_O41_PATIENT_2, "ORL_O41_PATIENT.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  ORL_O41_ORDER* getORL_O41_ORDER_1(size_t index = 0) {
    return (ORL_O41_ORDER*)this->getObjectSafe(index, ORL_O41_ORL_O41_ORDER_1);
  }
  ORL_O41_PATIENT* getORL_O41_PATIENT_2(size_t index = 0) {
    return (ORL_O41_PATIENT*)this->getObjectSafe(index, ORL_O41_ORL_O41_PATIENT_2);
  }

  /* Checker list */
  bool isORL_O41_ORDER_1(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_ORL_O41_ORDER_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isORL_O41_PATIENT_2(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_ORL_O41_PATIENT_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* ORL_O41_RESPONSE */

/* PATIENT */
struct ORL_O41_PATIENT : public HL7Group {
  ORL_O41_PATIENT() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    ORL_O41_PID_1,
    ORL_O41_PRT_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "ORL_O41_PATIENT"; }
  ORL_O41_PATIENT* create() const { return new ORL_O41_PATIENT(); }

 private:
  /* Initialize object */
  void init() {
    setName("ORL_O41.PATIENT");
    addObject<PID>(ORL_O41_PID_1, "PID.1", HL7::optional, HL7::repetition_on);
    addObject<PRT>(ORL_O41_PRT_2, "PRT.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  PID* getPID_1(size_t index = 0) {
    return (PID*)this->getObjectSafe(index, ORL_O41_PID_1);
  }
  PRT* getPRT_2(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, ORL_O41_PRT_2);
  }

  /* Checker list */
  bool isPID_1(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_PID_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_2(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_PRT_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* ORL_O41_PATIENT */

/* ORDER */
struct ORL_O41_ORDER : public HL7Group {
  ORL_O41_ORDER() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    ORL_O41_ORC_1,
    ORL_O41_ORL_O41_OBSERVATION_REQUEST_2,
    ORL_O41_ORL_O41_TIMING_3,
    ORL_O41_PRT_4,
    FIELD_ID_MAX
  };

  const char* className() const { return "ORL_O41_ORDER"; }
  ORL_O41_ORDER* create() const { return new ORL_O41_ORDER(); }

 private:
  /* Initialize object */
  void init() {
    setName("ORL_O41.ORDER");
    addObject<ORC>(ORL_O41_ORC_1, "ORC.1", HL7::optional, HL7::repetition_on);
    addObject<ORL_O41_OBSERVATION_REQUEST>(ORL_O41_ORL_O41_OBSERVATION_REQUEST_2, "ORL_O41_OBSERVATION_REQUEST.2", HL7::optional, HL7::repetition_on);
    addObject<ORL_O41_TIMING>(ORL_O41_ORL_O41_TIMING_3, "ORL_O41_TIMING.3", HL7::optional, HL7::repetition_on);
    addObject<PRT>(ORL_O41_PRT_4, "PRT.4", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  ORC* getORC_1(size_t index = 0) {
    return (ORC*)this->getObjectSafe(index, ORL_O41_ORC_1);
  }
  ORL_O41_OBSERVATION_REQUEST* getORL_O41_OBSERVATION_REQUEST_2(size_t index = 0) {
    return (ORL_O41_OBSERVATION_REQUEST*)this->getObjectSafe(index, ORL_O41_ORL_O41_OBSERVATION_REQUEST_2);
  }
  ORL_O41_TIMING* getORL_O41_TIMING_3(size_t index = 0) {
    return (ORL_O41_TIMING*)this->getObjectSafe(index, ORL_O41_ORL_O41_TIMING_3);
  }
  PRT* getPRT_4(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, ORL_O41_PRT_4);
  }

  /* Checker list */
  bool isORC_1(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_ORC_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isORL_O41_OBSERVATION_REQUEST_2(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_ORL_O41_OBSERVATION_REQUEST_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isORL_O41_TIMING_3(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_ORL_O41_TIMING_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_4(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_PRT_4) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* ORL_O41_ORDER */

/* TIMING */
struct ORL_O41_TIMING : public HL7Group {
  ORL_O41_TIMING() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    ORL_O41_TQ1_1,
    ORL_O41_TQ2_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "ORL_O41_TIMING"; }
  ORL_O41_TIMING* create() const { return new ORL_O41_TIMING(); }

 private:
  /* Initialize object */
  void init() {
    setName("ORL_O41.TIMING");
    addObject<TQ1>(ORL_O41_TQ1_1, "TQ1.1", HL7::optional, HL7::repetition_on);
    addObject<TQ2>(ORL_O41_TQ2_2, "TQ2.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  TQ1* getTQ1_1(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, ORL_O41_TQ1_1);
  }
  TQ2* getTQ2_2(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, ORL_O41_TQ2_2);
  }

  /* Checker list */
  bool isTQ1_1(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_TQ1_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_2(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_TQ2_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* ORL_O41_TIMING */

/* OBSERVATION_REQUEST */
struct ORL_O41_OBSERVATION_REQUEST : public HL7Group {
  ORL_O41_OBSERVATION_REQUEST() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    ORL_O41_OBR_1,
    ORL_O41_ORL_O41_SPECIMEN_2,
    ORL_O41_PRT_3,
    FIELD_ID_MAX
  };

  const char* className() const { return "ORL_O41_OBSERVATION_REQUEST"; }
  ORL_O41_OBSERVATION_REQUEST* create() const { return new ORL_O41_OBSERVATION_REQUEST(); }

 private:
  /* Initialize object */
  void init() {
    setName("ORL_O41.OBSERVATION_REQUEST");
    addObject<OBR>(ORL_O41_OBR_1, "OBR.1", HL7::optional, HL7::repetition_on);
    addObject<ORL_O41_SPECIMEN>(ORL_O41_ORL_O41_SPECIMEN_2, "ORL_O41_SPECIMEN.2", HL7::optional, HL7::repetition_on);
    addObject<PRT>(ORL_O41_PRT_3, "PRT.3", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  OBR* getOBR_1(size_t index = 0) {
    return (OBR*)this->getObjectSafe(index, ORL_O41_OBR_1);
  }
  ORL_O41_SPECIMEN* getORL_O41_SPECIMEN_2(size_t index = 0) {
    return (ORL_O41_SPECIMEN*)this->getObjectSafe(index, ORL_O41_ORL_O41_SPECIMEN_2);
  }
  PRT* getPRT_3(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, ORL_O41_PRT_3);
  }

  /* Checker list */
  bool isOBR_1(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_OBR_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isORL_O41_SPECIMEN_2(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_ORL_O41_SPECIMEN_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_3(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_PRT_3) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* ORL_O41_OBSERVATION_REQUEST */

/* SPECIMEN */
struct ORL_O41_SPECIMEN : public HL7Group {
  ORL_O41_SPECIMEN() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    ORL_O41_SAC_1,
    ORL_O41_SPM_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "ORL_O41_SPECIMEN"; }
  ORL_O41_SPECIMEN* create() const { return new ORL_O41_SPECIMEN(); }

 private:
  /* Initialize object */
  void init() {
    setName("ORL_O41.SPECIMEN");
    addObject<SAC>(ORL_O41_SAC_1, "SAC.1", HL7::optional, HL7::repetition_on);
    addObject<SPM>(ORL_O41_SPM_2, "SPM.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  SAC* getSAC_1(size_t index = 0) {
    return (SAC*)this->getObjectSafe(index, ORL_O41_SAC_1);
  }
  SPM* getSPM_2(size_t index = 0) {
    return (SPM*)this->getObjectSafe(index, ORL_O41_SPM_2);
  }

  /* Checker list */
  bool isSAC_1(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_SAC_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isSPM_2(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_SPM_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* ORL_O41_SPECIMEN */

/* ORL_O41 */
struct ORL_O41 : public HL7Message {
  ORL_O41() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    ORL_O41_MSH_1,
    ORL_O41_MSA_2,
    ORL_O41_ERR_3,
    ORL_O41_SFT_4,
    ORL_O41_UAC_5,
    ORL_O41_NTE_6,
    ORL_O41_PID_10,
    ORL_O41_PRT_11,
    ORL_O41_PID_12,
    ORL_O41_PRT_13,
    ORL_O41_ORC_14,
    ORL_O41_PRT_15,
    ORL_O41_TQ1_18,
    ORL_O41_TQ2_19,
    ORL_O41_TQ1_20,
    ORL_O41_TQ2_21,
    ORL_O41_OBR_22,
    ORL_O41_PRT_23,
    ORL_O41_SPM_25,
    ORL_O41_SAC_26,
    FIELD_ID_MAX
  };

  const char* className() const { return "ORL_O41"; }
  ORL_O41* create() const { return new ORL_O41(); }

 private:
  /* Initialize object */
  void init() {
    setName("ORL_O41");
    addObject<MSH>(ORL_O41_MSH_1, "MSH.1", HL7::initialized, HL7::repetition_off);
    addObject<MSA>(ORL_O41_MSA_2, "MSA.2", HL7::initialized, HL7::repetition_off);
    addObject<ERR>(ORL_O41_ERR_3, "ERR.3", HL7::optional, HL7::repetition_on);
    addObject<SFT>(ORL_O41_SFT_4, "SFT.4", HL7::optional, HL7::repetition_on);
    addObject<UAC>(ORL_O41_UAC_5, "UAC.5", HL7::optional, HL7::repetition_off);
    addObject<NTE>(ORL_O41_NTE_6, "NTE.6", HL7::optional, HL7::repetition_on);
    addObject<PID>(ORL_O41_PID_10, "PID.10", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(ORL_O41_PRT_11, "PRT.11", HL7::optional, HL7::repetition_off);
    addObject<PID>(ORL_O41_PID_12, "PID.12", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(ORL_O41_PRT_13, "PRT.13", HL7::optional, HL7::repetition_off);
    addObject<ORC>(ORL_O41_ORC_14, "ORC.14", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(ORL_O41_PRT_15, "PRT.15", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(ORL_O41_TQ1_18, "TQ1.18", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(ORL_O41_TQ2_19, "TQ2.19", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(ORL_O41_TQ1_20, "TQ1.20", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(ORL_O41_TQ2_21, "TQ2.21", HL7::optional, HL7::repetition_off);
    addObject<OBR>(ORL_O41_OBR_22, "OBR.22", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(ORL_O41_PRT_23, "PRT.23", HL7::optional, HL7::repetition_off);
    addObject<SPM>(ORL_O41_SPM_25, "SPM.25", HL7::initialized, HL7::repetition_off);
    addObject<SAC>(ORL_O41_SAC_26, "SAC.26", HL7::optional, HL7::repetition_off);
  }

 public:
  /* Getters list */
  MSH* getMSH_1(size_t index = 0) {
    return (MSH*)this->getObjectSafe(index, ORL_O41_MSH_1);
  }
  MSA* getMSA_2(size_t index = 0) {
    return (MSA*)this->getObjectSafe(index, ORL_O41_MSA_2);
  }
  ERR* getERR_3(size_t index = 0) {
    return (ERR*)this->getObjectSafe(index, ORL_O41_ERR_3);
  }
  SFT* getSFT_4(size_t index = 0) {
    return (SFT*)this->getObjectSafe(index, ORL_O41_SFT_4);
  }
  UAC* getUAC_5(size_t index = 0) {
    return (UAC*)this->getObjectSafe(index, ORL_O41_UAC_5);
  }
  NTE* getNTE_6(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, ORL_O41_NTE_6);
  }
  PID* getPID_10(size_t index = 0) {
    return (PID*)this->getObjectSafe(index, ORL_O41_PID_10);
  }
  PRT* getPRT_11(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, ORL_O41_PRT_11);
  }
  PID* getPID_12(size_t index = 0) {
    return (PID*)this->getObjectSafe(index, ORL_O41_PID_12);
  }
  PRT* getPRT_13(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, ORL_O41_PRT_13);
  }
  ORC* getORC_14(size_t index = 0) {
    return (ORC*)this->getObjectSafe(index, ORL_O41_ORC_14);
  }
  PRT* getPRT_15(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, ORL_O41_PRT_15);
  }
  TQ1* getTQ1_18(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, ORL_O41_TQ1_18);
  }
  TQ2* getTQ2_19(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, ORL_O41_TQ2_19);
  }
  TQ1* getTQ1_20(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, ORL_O41_TQ1_20);
  }
  TQ2* getTQ2_21(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, ORL_O41_TQ2_21);
  }
  OBR* getOBR_22(size_t index = 0) {
    return (OBR*)this->getObjectSafe(index, ORL_O41_OBR_22);
  }
  PRT* getPRT_23(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, ORL_O41_PRT_23);
  }
  SPM* getSPM_25(size_t index = 0) {
    return (SPM*)this->getObjectSafe(index, ORL_O41_SPM_25);
  }
  SAC* getSAC_26(size_t index = 0) {
    return (SAC*)this->getObjectSafe(index, ORL_O41_SAC_26);
  }

  /* Checker list */
  bool isMSH_1(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_MSH_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isMSA_2(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_MSA_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isERR_3(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_ERR_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isSFT_4(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_SFT_4) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isUAC_5(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_UAC_5) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_6(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_NTE_6) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPID_10(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_PID_10) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_11(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_PRT_11) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPID_12(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_PID_12) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_13(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_PRT_13) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isORC_14(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_ORC_14) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_15(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_PRT_15) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_18(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_TQ1_18) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_19(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_TQ2_19) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_20(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_TQ1_20) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_21(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_TQ2_21) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBR_22(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_OBR_22) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_23(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_PRT_23) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isSPM_25(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_SPM_25) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isSAC_26(size_t index = 0) {
    try {
      return this->getObject(index, ORL_O41_SAC_26) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* ORL_O41_ */
} /* namespace HL7_281 */
#endif /*  __ORL_O41__281_H__ */
