/*
 * hacca - C Toolkit for the HL7 Protocol
 *
 * Warning: This file was automatically generated by [hawk], please do not edit.
 *          Thu 25 Jun 19:05:54 CEST 2020
 *
 * R. Carbone (rocco@tecsiel.it)
 * Jun 2020
 *
 * SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * This file was developed as part of the ongoing activities related
 * to the design, implementation and execution of interoperability tests
 * between hacca-based versus AurigaHL7-based applications.
 *
 * In more details I decided to extend AurigaHL7 C++ Library with header files
 * implementing HL7 structures of the version 2.8.1 of the protocol (April 2014)
 * because the version 2.4 distributed with AurigaHL7 is a bit outdated (October 2000).
 *
 * All files in this fork was automatically generated by hacca-based tool [hawk]
 * and strictly follow the syntax and convention originally defined
 * by Auriga HL7 C++ Library just as form of continuity, convenience
 * and respect for their superb work.
 */


#ifndef __PMU_B07__281_H__
#define __PMU_B07__281_H__

#include "../../common/Util.h"
#include "../segment/CER.h"
#include "../segment/EVN.h"
#include "../segment/MSH.h"
#include "../segment/PRA.h"
#include "../segment/PRT.h"
#include "../segment/ROL.h"
#include "../segment/SFT.h"
#include "../segment/STF.h"
#include "../segment/UAC.h"

namespace HL7_281 {

/* Internal structures/groups */
struct PMU_B07_CERTIFICATE; /* CERTIFICATE */

/* CERTIFICATE */
struct PMU_B07_CERTIFICATE : public HL7Group {
  PMU_B07_CERTIFICATE() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    PMU_B07_CER_1,
    PMU_B07_PRT_2,
    PMU_B07_ROL_3,
    FIELD_ID_MAX
  };

  const char* className() const { return "PMU_B07_CERTIFICATE"; }
  PMU_B07_CERTIFICATE* create() const { return new PMU_B07_CERTIFICATE(); }

 private:
  /* Initialize object */
  void init() {
    setName("PMU_B07.CERTIFICATE");
    addObject<CER>(PMU_B07_CER_1, "CER.1", HL7::optional, HL7::repetition_on);
    addObject<PRT>(PMU_B07_PRT_2, "PRT.2", HL7::optional, HL7::repetition_on);
    addObject<ROL>(PMU_B07_ROL_3, "ROL.3", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  CER* getCER_1(size_t index = 0) {
    return (CER*)this->getObjectSafe(index, PMU_B07_CER_1);
  }
  PRT* getPRT_2(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, PMU_B07_PRT_2);
  }
  ROL* getROL_3(size_t index = 0) {
    return (ROL*)this->getObjectSafe(index, PMU_B07_ROL_3);
  }

  /* Checker list */
  bool isCER_1(size_t index = 0) {
    try {
      return this->getObject(index, PMU_B07_CER_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_2(size_t index = 0) {
    try {
      return this->getObject(index, PMU_B07_PRT_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isROL_3(size_t index = 0) {
    try {
      return this->getObject(index, PMU_B07_ROL_3) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* PMU_B07_CERTIFICATE */

/* PMU_B07 */
struct PMU_B07 : public HL7Message {
  PMU_B07() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    PMU_B07_MSH_1,
    PMU_B07_SFT_2,
    PMU_B07_UAC_3,
    PMU_B07_EVN_4,
    PMU_B07_STF_5,
    PMU_B07_PRA_6,
    PMU_B07_CER_8,
    PMU_B07_PRT_9,
    PMU_B07_ROL_10,
    FIELD_ID_MAX
  };

  const char* className() const { return "PMU_B07"; }
  PMU_B07* create() const { return new PMU_B07(); }

 private:
  /* Initialize object */
  void init() {
    setName("PMU_B07");
    addObject<MSH>(PMU_B07_MSH_1, "MSH.1", HL7::initialized, HL7::repetition_off);
    addObject<SFT>(PMU_B07_SFT_2, "SFT.2", HL7::optional, HL7::repetition_on);
    addObject<UAC>(PMU_B07_UAC_3, "UAC.3", HL7::optional, HL7::repetition_off);
    addObject<EVN>(PMU_B07_EVN_4, "EVN.4", HL7::initialized, HL7::repetition_off);
    addObject<STF>(PMU_B07_STF_5, "STF.5", HL7::initialized, HL7::repetition_off);
    addObject<PRA>(PMU_B07_PRA_6, "PRA.6", HL7::optional, HL7::repetition_off);
    addObject<CER>(PMU_B07_CER_8, "CER.8", HL7::initialized, HL7::repetition_off);
    addObject<PRT>(PMU_B07_PRT_9, "PRT.9", HL7::optional, HL7::repetition_off);
    addObject<ROL>(PMU_B07_ROL_10, "ROL.10", HL7::optional, HL7::repetition_off);
  }

 public:
  /* Getters list */
  MSH* getMSH_1(size_t index = 0) {
    return (MSH*)this->getObjectSafe(index, PMU_B07_MSH_1);
  }
  SFT* getSFT_2(size_t index = 0) {
    return (SFT*)this->getObjectSafe(index, PMU_B07_SFT_2);
  }
  UAC* getUAC_3(size_t index = 0) {
    return (UAC*)this->getObjectSafe(index, PMU_B07_UAC_3);
  }
  EVN* getEVN_4(size_t index = 0) {
    return (EVN*)this->getObjectSafe(index, PMU_B07_EVN_4);
  }
  STF* getSTF_5(size_t index = 0) {
    return (STF*)this->getObjectSafe(index, PMU_B07_STF_5);
  }
  PRA* getPRA_6(size_t index = 0) {
    return (PRA*)this->getObjectSafe(index, PMU_B07_PRA_6);
  }
  CER* getCER_8(size_t index = 0) {
    return (CER*)this->getObjectSafe(index, PMU_B07_CER_8);
  }
  PRT* getPRT_9(size_t index = 0) {
    return (PRT*)this->getObjectSafe(index, PMU_B07_PRT_9);
  }
  ROL* getROL_10(size_t index = 0) {
    return (ROL*)this->getObjectSafe(index, PMU_B07_ROL_10);
  }

  /* Checker list */
  bool isMSH_1(size_t index = 0) {
    try {
      return this->getObject(index, PMU_B07_MSH_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isSFT_2(size_t index = 0) {
    try {
      return this->getObject(index, PMU_B07_SFT_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isUAC_3(size_t index = 0) {
    try {
      return this->getObject(index, PMU_B07_UAC_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isEVN_4(size_t index = 0) {
    try {
      return this->getObject(index, PMU_B07_EVN_4) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isSTF_5(size_t index = 0) {
    try {
      return this->getObject(index, PMU_B07_STF_5) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRA_6(size_t index = 0) {
    try {
      return this->getObject(index, PMU_B07_PRA_6) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isCER_8(size_t index = 0) {
    try {
      return this->getObject(index, PMU_B07_CER_8) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPRT_9(size_t index = 0) {
    try {
      return this->getObject(index, PMU_B07_PRT_9) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isROL_10(size_t index = 0) {
    try {
      return this->getObject(index, PMU_B07_ROL_10) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* PMU_B07_ */
} /* namespace HL7_281 */
#endif /*  __PMU_B07__281_H__ */
