/*
 * hacca - C Toolkit for the HL7 Protocol
 *
 * Warning: This file was automatically generated by [hawk], please do not edit.
 *          Thu 25 Jun 19:07:06 CEST 2020
 *
 * R. Carbone (rocco@tecsiel.it)
 * Jun 2020
 *
 * SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * This file was developed as part of the ongoing activities related
 * to the design, implementation and execution of interoperability tests
 * between hacca-based versus AurigaHL7-based applications.
 *
 * In more details I decided to extend AurigaHL7 C++ Library with header files
 * implementing HL7 structures of the version 2.8.1 of the protocol (April 2014)
 * because the version 2.4 distributed with AurigaHL7 is a bit outdated (October 2000).
 *
 * All files in this fork was automatically generated by hacca-based tool [hawk]
 * and strictly follow the syntax and convention originally defined
 * by Auriga HL7 C++ Library just as form of continuity, convenience
 * and respect for their superb work.
 */


#ifndef __RSP_Z86__281_H__
#define __RSP_Z86__281_H__

#include "../../common/Util.h"
#include "../segment/AL1.h"
#include "../segment/DSC.h"
#include "../segment/ERR.h"
#include "../segment/MSA.h"
#include "../segment/MSH.h"
#include "../segment/NTE.h"
#include "../segment/OBX.h"
#include "../segment/ORC.h"
#include "../segment/PD1.h"
#include "../segment/PID.h"
#include "../segment/QAK.h"
#include "../segment/QPD.h"
#include "../segment/RXA.h"
#include "../segment/RXC.h"
#include "../segment/RXD.h"
#include "../segment/RXE.h"
#include "../segment/RXG.h"
#include "../segment/RXO.h"
#include "../segment/RXR.h"
#include "../segment/SFT.h"
#include "../segment/TQ1.h"
#include "../segment/TQ2.h"
#include "../segment/UAC.h"

namespace HL7_281 {

/* Internal structures/groups */
struct RSP_Z86_QUERY_RESPONSE; /* QUERY_RESPONSE */
struct RSP_Z86_PATIENT; /* PATIENT */
struct RSP_Z86_COMMON_ORDER; /* COMMON_ORDER */
struct RSP_Z86_TIMING; /* TIMING */
struct RSP_Z86_ORDER_DETAIL; /* ORDER_DETAIL */
struct RSP_Z86_ENCODED_ORDER; /* ENCODED_ORDER */
struct RSP_Z86_DISPENSE; /* DISPENSE */
struct RSP_Z86_GIVE; /* GIVE */
struct RSP_Z86_ADMINISTRATION; /* ADMINISTRATION */
struct RSP_Z86_OBSERVATION; /* OBSERVATION */
struct RSP_Z86_TIMING_ENCODED; /* TIMING_ENCODED */
struct RSP_Z86_TIMING_ENCODED; /* TIMING_ENCODED */
struct RSP_Z86_TIMING_ENCODED; /* TIMING_ENCODED */
struct RSP_Z86_TIMING_ENCODED; /* TIMING_ENCODED */
struct RSP_Z86_TIMING_ENCODED; /* TIMING_ENCODED */

/* QUERY_RESPONSE */
struct RSP_Z86_QUERY_RESPONSE : public HL7Group {
  RSP_Z86_QUERY_RESPONSE() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    RSP_Z86_RSP_Z86_COMMON_ORDER_1,
    RSP_Z86_RSP_Z86_PATIENT_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "RSP_Z86_QUERY_RESPONSE"; }
  RSP_Z86_QUERY_RESPONSE* create() const { return new RSP_Z86_QUERY_RESPONSE(); }

 private:
  /* Initialize object */
  void init() {
    setName("RSP_Z86.QUERY_RESPONSE");
    addObject<RSP_Z86_COMMON_ORDER>(RSP_Z86_RSP_Z86_COMMON_ORDER_1, "RSP_Z86_COMMON_ORDER.1", HL7::optional, HL7::repetition_on);
    addObject<RSP_Z86_PATIENT>(RSP_Z86_RSP_Z86_PATIENT_2, "RSP_Z86_PATIENT.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  RSP_Z86_COMMON_ORDER* getRSP_Z86_COMMON_ORDER_1(size_t index = 0) {
    return (RSP_Z86_COMMON_ORDER*)this->getObjectSafe(index, RSP_Z86_RSP_Z86_COMMON_ORDER_1);
  }
  RSP_Z86_PATIENT* getRSP_Z86_PATIENT_2(size_t index = 0) {
    return (RSP_Z86_PATIENT*)this->getObjectSafe(index, RSP_Z86_RSP_Z86_PATIENT_2);
  }

  /* Checker list */
  bool isRSP_Z86_COMMON_ORDER_1(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RSP_Z86_COMMON_ORDER_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRSP_Z86_PATIENT_2(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RSP_Z86_PATIENT_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* RSP_Z86_QUERY_RESPONSE */

/* PATIENT */
struct RSP_Z86_PATIENT : public HL7Group {
  RSP_Z86_PATIENT() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    RSP_Z86_AL1_1,
    RSP_Z86_NTE_2,
    RSP_Z86_PD1_3,
    RSP_Z86_PID_4,
    FIELD_ID_MAX
  };

  const char* className() const { return "RSP_Z86_PATIENT"; }
  RSP_Z86_PATIENT* create() const { return new RSP_Z86_PATIENT(); }

 private:
  /* Initialize object */
  void init() {
    setName("RSP_Z86.PATIENT");
    addObject<AL1>(RSP_Z86_AL1_1, "AL1.1", HL7::optional, HL7::repetition_on);
    addObject<NTE>(RSP_Z86_NTE_2, "NTE.2", HL7::optional, HL7::repetition_on);
    addObject<PD1>(RSP_Z86_PD1_3, "PD1.3", HL7::optional, HL7::repetition_on);
    addObject<PID>(RSP_Z86_PID_4, "PID.4", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  AL1* getAL1_1(size_t index = 0) {
    return (AL1*)this->getObjectSafe(index, RSP_Z86_AL1_1);
  }
  NTE* getNTE_2(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, RSP_Z86_NTE_2);
  }
  PD1* getPD1_3(size_t index = 0) {
    return (PD1*)this->getObjectSafe(index, RSP_Z86_PD1_3);
  }
  PID* getPID_4(size_t index = 0) {
    return (PID*)this->getObjectSafe(index, RSP_Z86_PID_4);
  }

  /* Checker list */
  bool isAL1_1(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_AL1_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_2(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_NTE_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPD1_3(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_PD1_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPID_4(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_PID_4) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* RSP_Z86_PATIENT */

/* COMMON_ORDER */
struct RSP_Z86_COMMON_ORDER : public HL7Group {
  RSP_Z86_COMMON_ORDER() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    RSP_Z86_ORC_1,
    RSP_Z86_RSP_Z86_ADMINISTRATION_2,
    RSP_Z86_RSP_Z86_DISPENSE_3,
    RSP_Z86_RSP_Z86_ENCODED_ORDER_4,
    RSP_Z86_RSP_Z86_GIVE_5,
    RSP_Z86_RSP_Z86_OBSERVATION_6,
    RSP_Z86_RSP_Z86_ORDER_DETAIL_7,
    RSP_Z86_RSP_Z86_TIMING_8,
    FIELD_ID_MAX
  };

  const char* className() const { return "RSP_Z86_COMMON_ORDER"; }
  RSP_Z86_COMMON_ORDER* create() const { return new RSP_Z86_COMMON_ORDER(); }

 private:
  /* Initialize object */
  void init() {
    setName("RSP_Z86.COMMON_ORDER");
    addObject<ORC>(RSP_Z86_ORC_1, "ORC.1", HL7::optional, HL7::repetition_on);
    addObject<RSP_Z86_ADMINISTRATION>(RSP_Z86_RSP_Z86_ADMINISTRATION_2, "RSP_Z86_ADMINISTRATION.2", HL7::optional, HL7::repetition_on);
    addObject<RSP_Z86_DISPENSE>(RSP_Z86_RSP_Z86_DISPENSE_3, "RSP_Z86_DISPENSE.3", HL7::optional, HL7::repetition_on);
    addObject<RSP_Z86_ENCODED_ORDER>(RSP_Z86_RSP_Z86_ENCODED_ORDER_4, "RSP_Z86_ENCODED_ORDER.4", HL7::optional, HL7::repetition_on);
    addObject<RSP_Z86_GIVE>(RSP_Z86_RSP_Z86_GIVE_5, "RSP_Z86_GIVE.5", HL7::optional, HL7::repetition_on);
    addObject<RSP_Z86_OBSERVATION>(RSP_Z86_RSP_Z86_OBSERVATION_6, "RSP_Z86_OBSERVATION.6", HL7::optional, HL7::repetition_on);
    addObject<RSP_Z86_ORDER_DETAIL>(RSP_Z86_RSP_Z86_ORDER_DETAIL_7, "RSP_Z86_ORDER_DETAIL.7", HL7::optional, HL7::repetition_on);
    addObject<RSP_Z86_TIMING>(RSP_Z86_RSP_Z86_TIMING_8, "RSP_Z86_TIMING.8", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  ORC* getORC_1(size_t index = 0) {
    return (ORC*)this->getObjectSafe(index, RSP_Z86_ORC_1);
  }
  RSP_Z86_ADMINISTRATION* getRSP_Z86_ADMINISTRATION_2(size_t index = 0) {
    return (RSP_Z86_ADMINISTRATION*)this->getObjectSafe(index, RSP_Z86_RSP_Z86_ADMINISTRATION_2);
  }
  RSP_Z86_DISPENSE* getRSP_Z86_DISPENSE_3(size_t index = 0) {
    return (RSP_Z86_DISPENSE*)this->getObjectSafe(index, RSP_Z86_RSP_Z86_DISPENSE_3);
  }
  RSP_Z86_ENCODED_ORDER* getRSP_Z86_ENCODED_ORDER_4(size_t index = 0) {
    return (RSP_Z86_ENCODED_ORDER*)this->getObjectSafe(index, RSP_Z86_RSP_Z86_ENCODED_ORDER_4);
  }
  RSP_Z86_GIVE* getRSP_Z86_GIVE_5(size_t index = 0) {
    return (RSP_Z86_GIVE*)this->getObjectSafe(index, RSP_Z86_RSP_Z86_GIVE_5);
  }
  RSP_Z86_OBSERVATION* getRSP_Z86_OBSERVATION_6(size_t index = 0) {
    return (RSP_Z86_OBSERVATION*)this->getObjectSafe(index, RSP_Z86_RSP_Z86_OBSERVATION_6);
  }
  RSP_Z86_ORDER_DETAIL* getRSP_Z86_ORDER_DETAIL_7(size_t index = 0) {
    return (RSP_Z86_ORDER_DETAIL*)this->getObjectSafe(index, RSP_Z86_RSP_Z86_ORDER_DETAIL_7);
  }
  RSP_Z86_TIMING* getRSP_Z86_TIMING_8(size_t index = 0) {
    return (RSP_Z86_TIMING*)this->getObjectSafe(index, RSP_Z86_RSP_Z86_TIMING_8);
  }

  /* Checker list */
  bool isORC_1(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_ORC_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRSP_Z86_ADMINISTRATION_2(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RSP_Z86_ADMINISTRATION_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRSP_Z86_DISPENSE_3(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RSP_Z86_DISPENSE_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRSP_Z86_ENCODED_ORDER_4(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RSP_Z86_ENCODED_ORDER_4) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRSP_Z86_GIVE_5(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RSP_Z86_GIVE_5) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRSP_Z86_OBSERVATION_6(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RSP_Z86_OBSERVATION_6) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRSP_Z86_ORDER_DETAIL_7(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RSP_Z86_ORDER_DETAIL_7) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRSP_Z86_TIMING_8(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RSP_Z86_TIMING_8) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* RSP_Z86_COMMON_ORDER */

/* TIMING */
struct RSP_Z86_TIMING : public HL7Group {
  RSP_Z86_TIMING() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    RSP_Z86_TQ1_1,
    RSP_Z86_TQ2_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "RSP_Z86_TIMING"; }
  RSP_Z86_TIMING* create() const { return new RSP_Z86_TIMING(); }

 private:
  /* Initialize object */
  void init() {
    setName("RSP_Z86.TIMING");
    addObject<TQ1>(RSP_Z86_TQ1_1, "TQ1.1", HL7::optional, HL7::repetition_on);
    addObject<TQ2>(RSP_Z86_TQ2_2, "TQ2.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  TQ1* getTQ1_1(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, RSP_Z86_TQ1_1);
  }
  TQ2* getTQ2_2(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, RSP_Z86_TQ2_2);
  }

  /* Checker list */
  bool isTQ1_1(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ1_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_2(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ2_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* RSP_Z86_TIMING */

/* ORDER_DETAIL */
struct RSP_Z86_ORDER_DETAIL : public HL7Group {
  RSP_Z86_ORDER_DETAIL() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    RSP_Z86_RXC_1,
    RSP_Z86_RXO_2,
    RSP_Z86_RXR_3,
    FIELD_ID_MAX
  };

  const char* className() const { return "RSP_Z86_ORDER_DETAIL"; }
  RSP_Z86_ORDER_DETAIL* create() const { return new RSP_Z86_ORDER_DETAIL(); }

 private:
  /* Initialize object */
  void init() {
    setName("RSP_Z86.ORDER_DETAIL");
    addObject<RXC>(RSP_Z86_RXC_1, "RXC.1", HL7::optional, HL7::repetition_on);
    addObject<RXO>(RSP_Z86_RXO_2, "RXO.2", HL7::optional, HL7::repetition_on);
    addObject<RXR>(RSP_Z86_RXR_3, "RXR.3", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  RXC* getRXC_1(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_1);
  }
  RXO* getRXO_2(size_t index = 0) {
    return (RXO*)this->getObjectSafe(index, RSP_Z86_RXO_2);
  }
  RXR* getRXR_3(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_3);
  }

  /* Checker list */
  bool isRXC_1(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXO_2(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXO_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_3(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_3) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* RSP_Z86_ORDER_DETAIL */

/* ENCODED_ORDER */
struct RSP_Z86_ENCODED_ORDER : public HL7Group {
  RSP_Z86_ENCODED_ORDER() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    RSP_Z86_RSP_Z86_TIMING_ENCODED_1,
    RSP_Z86_RXC_2,
    RSP_Z86_RXE_3,
    RSP_Z86_RXR_4,
    FIELD_ID_MAX
  };

  const char* className() const { return "RSP_Z86_ENCODED_ORDER"; }
  RSP_Z86_ENCODED_ORDER* create() const { return new RSP_Z86_ENCODED_ORDER(); }

 private:
  /* Initialize object */
  void init() {
    setName("RSP_Z86.ENCODED_ORDER");
    addObject<RSP_Z86_TIMING_ENCODED>(RSP_Z86_RSP_Z86_TIMING_ENCODED_1, "RSP_Z86_TIMING_ENCODED.1", HL7::optional, HL7::repetition_on);
    addObject<RXC>(RSP_Z86_RXC_2, "RXC.2", HL7::optional, HL7::repetition_on);
    addObject<RXE>(RSP_Z86_RXE_3, "RXE.3", HL7::optional, HL7::repetition_on);
    addObject<RXR>(RSP_Z86_RXR_4, "RXR.4", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  RSP_Z86_TIMING_ENCODED* getRSP_Z86_TIMING_ENCODED_1(size_t index = 0) {
    return (RSP_Z86_TIMING_ENCODED*)this->getObjectSafe(index, RSP_Z86_RSP_Z86_TIMING_ENCODED_1);
  }
  RXC* getRXC_2(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_2);
  }
  RXE* getRXE_3(size_t index = 0) {
    return (RXE*)this->getObjectSafe(index, RSP_Z86_RXE_3);
  }
  RXR* getRXR_4(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_4);
  }

  /* Checker list */
  bool isRSP_Z86_TIMING_ENCODED_1(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RSP_Z86_TIMING_ENCODED_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_2(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXE_3(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXE_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_4(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_4) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* RSP_Z86_ENCODED_ORDER */

/* DISPENSE */
struct RSP_Z86_DISPENSE : public HL7Group {
  RSP_Z86_DISPENSE() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    RSP_Z86_RXC_1,
    RSP_Z86_RXD_2,
    RSP_Z86_RXR_3,
    FIELD_ID_MAX
  };

  const char* className() const { return "RSP_Z86_DISPENSE"; }
  RSP_Z86_DISPENSE* create() const { return new RSP_Z86_DISPENSE(); }

 private:
  /* Initialize object */
  void init() {
    setName("RSP_Z86.DISPENSE");
    addObject<RXC>(RSP_Z86_RXC_1, "RXC.1", HL7::optional, HL7::repetition_on);
    addObject<RXD>(RSP_Z86_RXD_2, "RXD.2", HL7::optional, HL7::repetition_on);
    addObject<RXR>(RSP_Z86_RXR_3, "RXR.3", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  RXC* getRXC_1(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_1);
  }
  RXD* getRXD_2(size_t index = 0) {
    return (RXD*)this->getObjectSafe(index, RSP_Z86_RXD_2);
  }
  RXR* getRXR_3(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_3);
  }

  /* Checker list */
  bool isRXC_1(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXD_2(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXD_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_3(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_3) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* RSP_Z86_DISPENSE */

/* GIVE */
struct RSP_Z86_GIVE : public HL7Group {
  RSP_Z86_GIVE() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    RSP_Z86_RXC_1,
    RSP_Z86_RXG_2,
    RSP_Z86_RXR_3,
    FIELD_ID_MAX
  };

  const char* className() const { return "RSP_Z86_GIVE"; }
  RSP_Z86_GIVE* create() const { return new RSP_Z86_GIVE(); }

 private:
  /* Initialize object */
  void init() {
    setName("RSP_Z86.GIVE");
    addObject<RXC>(RSP_Z86_RXC_1, "RXC.1", HL7::optional, HL7::repetition_on);
    addObject<RXG>(RSP_Z86_RXG_2, "RXG.2", HL7::optional, HL7::repetition_on);
    addObject<RXR>(RSP_Z86_RXR_3, "RXR.3", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  RXC* getRXC_1(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_1);
  }
  RXG* getRXG_2(size_t index = 0) {
    return (RXG*)this->getObjectSafe(index, RSP_Z86_RXG_2);
  }
  RXR* getRXR_3(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_3);
  }

  /* Checker list */
  bool isRXC_1(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXG_2(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXG_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_3(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_3) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* RSP_Z86_GIVE */

/* ADMINISTRATION */
struct RSP_Z86_ADMINISTRATION : public HL7Group {
  RSP_Z86_ADMINISTRATION() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    RSP_Z86_RXA_1,
    RSP_Z86_RXC_2,
    RSP_Z86_RXR_3,
    FIELD_ID_MAX
  };

  const char* className() const { return "RSP_Z86_ADMINISTRATION"; }
  RSP_Z86_ADMINISTRATION* create() const { return new RSP_Z86_ADMINISTRATION(); }

 private:
  /* Initialize object */
  void init() {
    setName("RSP_Z86.ADMINISTRATION");
    addObject<RXA>(RSP_Z86_RXA_1, "RXA.1", HL7::optional, HL7::repetition_on);
    addObject<RXC>(RSP_Z86_RXC_2, "RXC.2", HL7::optional, HL7::repetition_on);
    addObject<RXR>(RSP_Z86_RXR_3, "RXR.3", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  RXA* getRXA_1(size_t index = 0) {
    return (RXA*)this->getObjectSafe(index, RSP_Z86_RXA_1);
  }
  RXC* getRXC_2(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_2);
  }
  RXR* getRXR_3(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_3);
  }

  /* Checker list */
  bool isRXA_1(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXA_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_2(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_3(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_3) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* RSP_Z86_ADMINISTRATION */

/* OBSERVATION */
struct RSP_Z86_OBSERVATION : public HL7Group {
  RSP_Z86_OBSERVATION() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    RSP_Z86_NTE_1,
    RSP_Z86_OBX_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "RSP_Z86_OBSERVATION"; }
  RSP_Z86_OBSERVATION* create() const { return new RSP_Z86_OBSERVATION(); }

 private:
  /* Initialize object */
  void init() {
    setName("RSP_Z86.OBSERVATION");
    addObject<NTE>(RSP_Z86_NTE_1, "NTE.1", HL7::optional, HL7::repetition_on);
    addObject<OBX>(RSP_Z86_OBX_2, "OBX.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  NTE* getNTE_1(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, RSP_Z86_NTE_1);
  }
  OBX* getOBX_2(size_t index = 0) {
    return (OBX*)this->getObjectSafe(index, RSP_Z86_OBX_2);
  }

  /* Checker list */
  bool isNTE_1(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_NTE_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBX_2(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_OBX_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* RSP_Z86_OBSERVATION */

/* TIMING_ENCODED */
struct RSP_Z86_TIMING_ENCODED : public HL7Group {
  RSP_Z86_TIMING_ENCODED() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    RSP_Z86_TQ1_1,
    RSP_Z86_TQ2_2,
    FIELD_ID_MAX
  };

  const char* className() const { return "RSP_Z86_TIMING_ENCODED"; }
  RSP_Z86_TIMING_ENCODED* create() const { return new RSP_Z86_TIMING_ENCODED(); }

 private:
  /* Initialize object */
  void init() {
    setName("RSP_Z86.TIMING_ENCODED");
    addObject<TQ1>(RSP_Z86_TQ1_1, "TQ1.1", HL7::optional, HL7::repetition_on);
    addObject<TQ2>(RSP_Z86_TQ2_2, "TQ2.2", HL7::optional, HL7::repetition_on);
  }

 public:
  /* Getters list */
  TQ1* getTQ1_1(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, RSP_Z86_TQ1_1);
  }
  TQ2* getTQ2_2(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, RSP_Z86_TQ2_2);
  }

  /* Checker list */
  bool isTQ1_1(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ1_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_2(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ2_2) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* RSP_Z86_TIMING_ENCODED */

/* RSP_Z86 */
struct RSP_Z86 : public HL7Message {
  RSP_Z86() { this->init(); }
  /* Fields ID  */
  enum FIELD_ID {
    RSP_Z86_MSH_1,
    RSP_Z86_SFT_2,
    RSP_Z86_UAC_3,
    RSP_Z86_MSA_4,
    RSP_Z86_ERR_5,
    RSP_Z86_QAK_6,
    RSP_Z86_QPD_7,
    RSP_Z86_DSC_9,
    RSP_Z86_PID_12,
    RSP_Z86_PD1_13,
    RSP_Z86_NTE_14,
    RSP_Z86_AL1_15,
    RSP_Z86_PID_16,
    RSP_Z86_PD1_17,
    RSP_Z86_NTE_18,
    RSP_Z86_AL1_19,
    RSP_Z86_ORC_20,
    RSP_Z86_TQ1_28,
    RSP_Z86_TQ2_29,
    RSP_Z86_TQ1_30,
    RSP_Z86_TQ2_31,
    RSP_Z86_RXO_32,
    RSP_Z86_RXR_33,
    RSP_Z86_RXC_34,
    RSP_Z86_TQ1_35,
    RSP_Z86_TQ2_36,
    RSP_Z86_RXO_37,
    RSP_Z86_RXR_38,
    RSP_Z86_RXC_39,
    RSP_Z86_RXE_40,
    RSP_Z86_RXR_42,
    RSP_Z86_RXC_43,
    RSP_Z86_TQ1_44,
    RSP_Z86_TQ2_45,
    RSP_Z86_TQ1_46,
    RSP_Z86_TQ2_47,
    RSP_Z86_RXO_48,
    RSP_Z86_RXR_49,
    RSP_Z86_RXC_50,
    RSP_Z86_RXE_51,
    RSP_Z86_RXR_53,
    RSP_Z86_RXC_54,
    RSP_Z86_RXD_55,
    RSP_Z86_RXR_56,
    RSP_Z86_RXC_57,
    RSP_Z86_TQ1_58,
    RSP_Z86_TQ2_59,
    RSP_Z86_TQ1_60,
    RSP_Z86_TQ2_61,
    RSP_Z86_RXO_62,
    RSP_Z86_RXR_63,
    RSP_Z86_RXC_64,
    RSP_Z86_RXE_65,
    RSP_Z86_RXR_67,
    RSP_Z86_RXC_68,
    RSP_Z86_RXD_69,
    RSP_Z86_RXR_70,
    RSP_Z86_RXC_71,
    RSP_Z86_RXG_72,
    RSP_Z86_RXR_73,
    RSP_Z86_RXC_74,
    RSP_Z86_TQ1_75,
    RSP_Z86_TQ2_76,
    RSP_Z86_TQ1_77,
    RSP_Z86_TQ2_78,
    RSP_Z86_RXO_79,
    RSP_Z86_RXR_80,
    RSP_Z86_RXC_81,
    RSP_Z86_RXE_82,
    RSP_Z86_RXR_84,
    RSP_Z86_RXC_85,
    RSP_Z86_RXD_86,
    RSP_Z86_RXR_87,
    RSP_Z86_RXC_88,
    RSP_Z86_RXG_89,
    RSP_Z86_RXR_90,
    RSP_Z86_RXC_91,
    RSP_Z86_RXA_92,
    RSP_Z86_RXR_93,
    RSP_Z86_RXC_94,
    RSP_Z86_TQ1_95,
    RSP_Z86_TQ2_96,
    RSP_Z86_TQ1_97,
    RSP_Z86_TQ2_98,
    RSP_Z86_RXO_99,
    RSP_Z86_RXR_100,
    RSP_Z86_RXC_101,
    RSP_Z86_RXE_102,
    RSP_Z86_RXR_104,
    RSP_Z86_RXC_105,
    RSP_Z86_RXD_106,
    RSP_Z86_RXR_107,
    RSP_Z86_RXC_108,
    RSP_Z86_RXG_109,
    RSP_Z86_RXR_110,
    RSP_Z86_RXC_111,
    RSP_Z86_RXA_112,
    RSP_Z86_RXR_113,
    RSP_Z86_RXC_114,
    RSP_Z86_OBX_115,
    RSP_Z86_NTE_116,
    RSP_Z86_TQ1_117,
    RSP_Z86_TQ2_118,
    FIELD_ID_MAX
  };

  const char* className() const { return "RSP_Z86"; }
  RSP_Z86* create() const { return new RSP_Z86(); }

 private:
  /* Initialize object */
  void init() {
    setName("RSP_Z86");
    addObject<MSH>(RSP_Z86_MSH_1, "MSH.1", HL7::initialized, HL7::repetition_off);
    addObject<SFT>(RSP_Z86_SFT_2, "SFT.2", HL7::optional, HL7::repetition_on);
    addObject<UAC>(RSP_Z86_UAC_3, "UAC.3", HL7::optional, HL7::repetition_off);
    addObject<MSA>(RSP_Z86_MSA_4, "MSA.4", HL7::initialized, HL7::repetition_off);
    addObject<ERR>(RSP_Z86_ERR_5, "ERR.5", HL7::optional, HL7::repetition_off);
    addObject<QAK>(RSP_Z86_QAK_6, "QAK.6", HL7::initialized, HL7::repetition_off);
    addObject<QPD>(RSP_Z86_QPD_7, "QPD.7", HL7::initialized, HL7::repetition_off);
    addObject<DSC>(RSP_Z86_DSC_9, "DSC.9", HL7::optional, HL7::repetition_off);
    addObject<PID>(RSP_Z86_PID_12, "PID.12", HL7::initialized, HL7::repetition_off);
    addObject<PD1>(RSP_Z86_PD1_13, "PD1.13", HL7::optional, HL7::repetition_off);
    addObject<NTE>(RSP_Z86_NTE_14, "NTE.14", HL7::optional, HL7::repetition_off);
    addObject<AL1>(RSP_Z86_AL1_15, "AL1.15", HL7::optional, HL7::repetition_off);
    addObject<PID>(RSP_Z86_PID_16, "PID.16", HL7::initialized, HL7::repetition_off);
    addObject<PD1>(RSP_Z86_PD1_17, "PD1.17", HL7::optional, HL7::repetition_off);
    addObject<NTE>(RSP_Z86_NTE_18, "NTE.18", HL7::optional, HL7::repetition_off);
    addObject<AL1>(RSP_Z86_AL1_19, "AL1.19", HL7::optional, HL7::repetition_off);
    addObject<ORC>(RSP_Z86_ORC_20, "ORC.20", HL7::initialized, HL7::repetition_off);
    addObject<TQ1>(RSP_Z86_TQ1_28, "TQ1.28", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(RSP_Z86_TQ2_29, "TQ2.29", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(RSP_Z86_TQ1_30, "TQ1.30", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(RSP_Z86_TQ2_31, "TQ2.31", HL7::optional, HL7::repetition_off);
    addObject<RXO>(RSP_Z86_RXO_32, "RXO.32", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_33, "RXR.33", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_34, "RXC.34", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(RSP_Z86_TQ1_35, "TQ1.35", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(RSP_Z86_TQ2_36, "TQ2.36", HL7::optional, HL7::repetition_off);
    addObject<RXO>(RSP_Z86_RXO_37, "RXO.37", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_38, "RXR.38", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_39, "RXC.39", HL7::optional, HL7::repetition_off);
    addObject<RXE>(RSP_Z86_RXE_40, "RXE.40", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_42, "RXR.42", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_43, "RXC.43", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(RSP_Z86_TQ1_44, "TQ1.44", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(RSP_Z86_TQ2_45, "TQ2.45", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(RSP_Z86_TQ1_46, "TQ1.46", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(RSP_Z86_TQ2_47, "TQ2.47", HL7::optional, HL7::repetition_off);
    addObject<RXO>(RSP_Z86_RXO_48, "RXO.48", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_49, "RXR.49", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_50, "RXC.50", HL7::optional, HL7::repetition_off);
    addObject<RXE>(RSP_Z86_RXE_51, "RXE.51", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_53, "RXR.53", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_54, "RXC.54", HL7::optional, HL7::repetition_off);
    addObject<RXD>(RSP_Z86_RXD_55, "RXD.55", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_56, "RXR.56", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_57, "RXC.57", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(RSP_Z86_TQ1_58, "TQ1.58", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(RSP_Z86_TQ2_59, "TQ2.59", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(RSP_Z86_TQ1_60, "TQ1.60", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(RSP_Z86_TQ2_61, "TQ2.61", HL7::optional, HL7::repetition_off);
    addObject<RXO>(RSP_Z86_RXO_62, "RXO.62", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_63, "RXR.63", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_64, "RXC.64", HL7::optional, HL7::repetition_off);
    addObject<RXE>(RSP_Z86_RXE_65, "RXE.65", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_67, "RXR.67", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_68, "RXC.68", HL7::optional, HL7::repetition_off);
    addObject<RXD>(RSP_Z86_RXD_69, "RXD.69", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_70, "RXR.70", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_71, "RXC.71", HL7::optional, HL7::repetition_off);
    addObject<RXG>(RSP_Z86_RXG_72, "RXG.72", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_73, "RXR.73", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_74, "RXC.74", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(RSP_Z86_TQ1_75, "TQ1.75", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(RSP_Z86_TQ2_76, "TQ2.76", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(RSP_Z86_TQ1_77, "TQ1.77", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(RSP_Z86_TQ2_78, "TQ2.78", HL7::optional, HL7::repetition_off);
    addObject<RXO>(RSP_Z86_RXO_79, "RXO.79", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_80, "RXR.80", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_81, "RXC.81", HL7::optional, HL7::repetition_off);
    addObject<RXE>(RSP_Z86_RXE_82, "RXE.82", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_84, "RXR.84", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_85, "RXC.85", HL7::optional, HL7::repetition_off);
    addObject<RXD>(RSP_Z86_RXD_86, "RXD.86", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_87, "RXR.87", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_88, "RXC.88", HL7::optional, HL7::repetition_off);
    addObject<RXG>(RSP_Z86_RXG_89, "RXG.89", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_90, "RXR.90", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_91, "RXC.91", HL7::optional, HL7::repetition_off);
    addObject<RXA>(RSP_Z86_RXA_92, "RXA.92", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_93, "RXR.93", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_94, "RXC.94", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(RSP_Z86_TQ1_95, "TQ1.95", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(RSP_Z86_TQ2_96, "TQ2.96", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(RSP_Z86_TQ1_97, "TQ1.97", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(RSP_Z86_TQ2_98, "TQ2.98", HL7::optional, HL7::repetition_off);
    addObject<RXO>(RSP_Z86_RXO_99, "RXO.99", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_100, "RXR.100", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_101, "RXC.101", HL7::optional, HL7::repetition_off);
    addObject<RXE>(RSP_Z86_RXE_102, "RXE.102", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_104, "RXR.104", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_105, "RXC.105", HL7::optional, HL7::repetition_off);
    addObject<RXD>(RSP_Z86_RXD_106, "RXD.106", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_107, "RXR.107", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_108, "RXC.108", HL7::optional, HL7::repetition_off);
    addObject<RXG>(RSP_Z86_RXG_109, "RXG.109", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_110, "RXR.110", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_111, "RXC.111", HL7::optional, HL7::repetition_off);
    addObject<RXA>(RSP_Z86_RXA_112, "RXA.112", HL7::initialized, HL7::repetition_off);
    addObject<RXR>(RSP_Z86_RXR_113, "RXR.113", HL7::initialized, HL7::repetition_off);
    addObject<RXC>(RSP_Z86_RXC_114, "RXC.114", HL7::optional, HL7::repetition_off);
    addObject<OBX>(RSP_Z86_OBX_115, "OBX.115", HL7::optional, HL7::repetition_off);
    addObject<NTE>(RSP_Z86_NTE_116, "NTE.116", HL7::optional, HL7::repetition_off);
    addObject<TQ1>(RSP_Z86_TQ1_117, "TQ1.117", HL7::initialized, HL7::repetition_off);
    addObject<TQ2>(RSP_Z86_TQ2_118, "TQ2.118", HL7::optional, HL7::repetition_off);
  }

 public:
  /* Getters list */
  MSH* getMSH_1(size_t index = 0) {
    return (MSH*)this->getObjectSafe(index, RSP_Z86_MSH_1);
  }
  SFT* getSFT_2(size_t index = 0) {
    return (SFT*)this->getObjectSafe(index, RSP_Z86_SFT_2);
  }
  UAC* getUAC_3(size_t index = 0) {
    return (UAC*)this->getObjectSafe(index, RSP_Z86_UAC_3);
  }
  MSA* getMSA_4(size_t index = 0) {
    return (MSA*)this->getObjectSafe(index, RSP_Z86_MSA_4);
  }
  ERR* getERR_5(size_t index = 0) {
    return (ERR*)this->getObjectSafe(index, RSP_Z86_ERR_5);
  }
  QAK* getQAK_6(size_t index = 0) {
    return (QAK*)this->getObjectSafe(index, RSP_Z86_QAK_6);
  }
  QPD* getQPD_7(size_t index = 0) {
    return (QPD*)this->getObjectSafe(index, RSP_Z86_QPD_7);
  }
  DSC* getDSC_9(size_t index = 0) {
    return (DSC*)this->getObjectSafe(index, RSP_Z86_DSC_9);
  }
  PID* getPID_12(size_t index = 0) {
    return (PID*)this->getObjectSafe(index, RSP_Z86_PID_12);
  }
  PD1* getPD1_13(size_t index = 0) {
    return (PD1*)this->getObjectSafe(index, RSP_Z86_PD1_13);
  }
  NTE* getNTE_14(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, RSP_Z86_NTE_14);
  }
  AL1* getAL1_15(size_t index = 0) {
    return (AL1*)this->getObjectSafe(index, RSP_Z86_AL1_15);
  }
  PID* getPID_16(size_t index = 0) {
    return (PID*)this->getObjectSafe(index, RSP_Z86_PID_16);
  }
  PD1* getPD1_17(size_t index = 0) {
    return (PD1*)this->getObjectSafe(index, RSP_Z86_PD1_17);
  }
  NTE* getNTE_18(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, RSP_Z86_NTE_18);
  }
  AL1* getAL1_19(size_t index = 0) {
    return (AL1*)this->getObjectSafe(index, RSP_Z86_AL1_19);
  }
  ORC* getORC_20(size_t index = 0) {
    return (ORC*)this->getObjectSafe(index, RSP_Z86_ORC_20);
  }
  TQ1* getTQ1_28(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, RSP_Z86_TQ1_28);
  }
  TQ2* getTQ2_29(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, RSP_Z86_TQ2_29);
  }
  TQ1* getTQ1_30(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, RSP_Z86_TQ1_30);
  }
  TQ2* getTQ2_31(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, RSP_Z86_TQ2_31);
  }
  RXO* getRXO_32(size_t index = 0) {
    return (RXO*)this->getObjectSafe(index, RSP_Z86_RXO_32);
  }
  RXR* getRXR_33(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_33);
  }
  RXC* getRXC_34(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_34);
  }
  TQ1* getTQ1_35(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, RSP_Z86_TQ1_35);
  }
  TQ2* getTQ2_36(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, RSP_Z86_TQ2_36);
  }
  RXO* getRXO_37(size_t index = 0) {
    return (RXO*)this->getObjectSafe(index, RSP_Z86_RXO_37);
  }
  RXR* getRXR_38(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_38);
  }
  RXC* getRXC_39(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_39);
  }
  RXE* getRXE_40(size_t index = 0) {
    return (RXE*)this->getObjectSafe(index, RSP_Z86_RXE_40);
  }
  RXR* getRXR_42(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_42);
  }
  RXC* getRXC_43(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_43);
  }
  TQ1* getTQ1_44(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, RSP_Z86_TQ1_44);
  }
  TQ2* getTQ2_45(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, RSP_Z86_TQ2_45);
  }
  TQ1* getTQ1_46(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, RSP_Z86_TQ1_46);
  }
  TQ2* getTQ2_47(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, RSP_Z86_TQ2_47);
  }
  RXO* getRXO_48(size_t index = 0) {
    return (RXO*)this->getObjectSafe(index, RSP_Z86_RXO_48);
  }
  RXR* getRXR_49(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_49);
  }
  RXC* getRXC_50(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_50);
  }
  RXE* getRXE_51(size_t index = 0) {
    return (RXE*)this->getObjectSafe(index, RSP_Z86_RXE_51);
  }
  RXR* getRXR_53(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_53);
  }
  RXC* getRXC_54(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_54);
  }
  RXD* getRXD_55(size_t index = 0) {
    return (RXD*)this->getObjectSafe(index, RSP_Z86_RXD_55);
  }
  RXR* getRXR_56(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_56);
  }
  RXC* getRXC_57(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_57);
  }
  TQ1* getTQ1_58(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, RSP_Z86_TQ1_58);
  }
  TQ2* getTQ2_59(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, RSP_Z86_TQ2_59);
  }
  TQ1* getTQ1_60(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, RSP_Z86_TQ1_60);
  }
  TQ2* getTQ2_61(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, RSP_Z86_TQ2_61);
  }
  RXO* getRXO_62(size_t index = 0) {
    return (RXO*)this->getObjectSafe(index, RSP_Z86_RXO_62);
  }
  RXR* getRXR_63(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_63);
  }
  RXC* getRXC_64(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_64);
  }
  RXE* getRXE_65(size_t index = 0) {
    return (RXE*)this->getObjectSafe(index, RSP_Z86_RXE_65);
  }
  RXR* getRXR_67(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_67);
  }
  RXC* getRXC_68(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_68);
  }
  RXD* getRXD_69(size_t index = 0) {
    return (RXD*)this->getObjectSafe(index, RSP_Z86_RXD_69);
  }
  RXR* getRXR_70(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_70);
  }
  RXC* getRXC_71(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_71);
  }
  RXG* getRXG_72(size_t index = 0) {
    return (RXG*)this->getObjectSafe(index, RSP_Z86_RXG_72);
  }
  RXR* getRXR_73(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_73);
  }
  RXC* getRXC_74(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_74);
  }
  TQ1* getTQ1_75(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, RSP_Z86_TQ1_75);
  }
  TQ2* getTQ2_76(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, RSP_Z86_TQ2_76);
  }
  TQ1* getTQ1_77(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, RSP_Z86_TQ1_77);
  }
  TQ2* getTQ2_78(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, RSP_Z86_TQ2_78);
  }
  RXO* getRXO_79(size_t index = 0) {
    return (RXO*)this->getObjectSafe(index, RSP_Z86_RXO_79);
  }
  RXR* getRXR_80(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_80);
  }
  RXC* getRXC_81(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_81);
  }
  RXE* getRXE_82(size_t index = 0) {
    return (RXE*)this->getObjectSafe(index, RSP_Z86_RXE_82);
  }
  RXR* getRXR_84(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_84);
  }
  RXC* getRXC_85(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_85);
  }
  RXD* getRXD_86(size_t index = 0) {
    return (RXD*)this->getObjectSafe(index, RSP_Z86_RXD_86);
  }
  RXR* getRXR_87(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_87);
  }
  RXC* getRXC_88(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_88);
  }
  RXG* getRXG_89(size_t index = 0) {
    return (RXG*)this->getObjectSafe(index, RSP_Z86_RXG_89);
  }
  RXR* getRXR_90(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_90);
  }
  RXC* getRXC_91(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_91);
  }
  RXA* getRXA_92(size_t index = 0) {
    return (RXA*)this->getObjectSafe(index, RSP_Z86_RXA_92);
  }
  RXR* getRXR_93(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_93);
  }
  RXC* getRXC_94(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_94);
  }
  TQ1* getTQ1_95(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, RSP_Z86_TQ1_95);
  }
  TQ2* getTQ2_96(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, RSP_Z86_TQ2_96);
  }
  TQ1* getTQ1_97(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, RSP_Z86_TQ1_97);
  }
  TQ2* getTQ2_98(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, RSP_Z86_TQ2_98);
  }
  RXO* getRXO_99(size_t index = 0) {
    return (RXO*)this->getObjectSafe(index, RSP_Z86_RXO_99);
  }
  RXR* getRXR_100(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_100);
  }
  RXC* getRXC_101(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_101);
  }
  RXE* getRXE_102(size_t index = 0) {
    return (RXE*)this->getObjectSafe(index, RSP_Z86_RXE_102);
  }
  RXR* getRXR_104(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_104);
  }
  RXC* getRXC_105(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_105);
  }
  RXD* getRXD_106(size_t index = 0) {
    return (RXD*)this->getObjectSafe(index, RSP_Z86_RXD_106);
  }
  RXR* getRXR_107(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_107);
  }
  RXC* getRXC_108(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_108);
  }
  RXG* getRXG_109(size_t index = 0) {
    return (RXG*)this->getObjectSafe(index, RSP_Z86_RXG_109);
  }
  RXR* getRXR_110(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_110);
  }
  RXC* getRXC_111(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_111);
  }
  RXA* getRXA_112(size_t index = 0) {
    return (RXA*)this->getObjectSafe(index, RSP_Z86_RXA_112);
  }
  RXR* getRXR_113(size_t index = 0) {
    return (RXR*)this->getObjectSafe(index, RSP_Z86_RXR_113);
  }
  RXC* getRXC_114(size_t index = 0) {
    return (RXC*)this->getObjectSafe(index, RSP_Z86_RXC_114);
  }
  OBX* getOBX_115(size_t index = 0) {
    return (OBX*)this->getObjectSafe(index, RSP_Z86_OBX_115);
  }
  NTE* getNTE_116(size_t index = 0) {
    return (NTE*)this->getObjectSafe(index, RSP_Z86_NTE_116);
  }
  TQ1* getTQ1_117(size_t index = 0) {
    return (TQ1*)this->getObjectSafe(index, RSP_Z86_TQ1_117);
  }
  TQ2* getTQ2_118(size_t index = 0) {
    return (TQ2*)this->getObjectSafe(index, RSP_Z86_TQ2_118);
  }

  /* Checker list */
  bool isMSH_1(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_MSH_1) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isSFT_2(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_SFT_2) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isUAC_3(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_UAC_3) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isMSA_4(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_MSA_4) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isERR_5(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_ERR_5) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isQAK_6(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_QAK_6) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isQPD_7(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_QPD_7) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isDSC_9(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_DSC_9) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPID_12(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_PID_12) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPD1_13(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_PD1_13) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_14(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_NTE_14) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isAL1_15(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_AL1_15) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPID_16(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_PID_16) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isPD1_17(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_PD1_17) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_18(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_NTE_18) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isAL1_19(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_AL1_19) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isORC_20(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_ORC_20) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_28(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ1_28) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_29(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ2_29) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_30(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ1_30) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_31(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ2_31) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXO_32(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXO_32) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_33(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_33) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_34(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_34) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_35(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ1_35) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_36(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ2_36) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXO_37(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXO_37) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_38(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_38) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_39(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_39) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXE_40(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXE_40) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_42(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_42) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_43(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_43) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_44(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ1_44) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_45(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ2_45) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_46(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ1_46) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_47(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ2_47) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXO_48(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXO_48) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_49(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_49) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_50(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_50) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXE_51(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXE_51) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_53(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_53) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_54(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_54) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXD_55(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXD_55) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_56(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_56) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_57(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_57) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_58(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ1_58) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_59(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ2_59) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_60(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ1_60) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_61(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ2_61) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXO_62(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXO_62) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_63(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_63) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_64(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_64) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXE_65(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXE_65) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_67(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_67) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_68(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_68) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXD_69(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXD_69) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_70(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_70) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_71(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_71) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXG_72(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXG_72) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_73(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_73) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_74(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_74) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_75(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ1_75) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_76(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ2_76) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_77(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ1_77) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_78(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ2_78) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXO_79(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXO_79) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_80(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_80) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_81(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_81) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXE_82(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXE_82) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_84(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_84) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_85(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_85) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXD_86(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXD_86) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_87(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_87) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_88(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_88) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXG_89(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXG_89) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_90(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_90) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_91(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_91) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXA_92(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXA_92) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_93(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_93) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_94(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_94) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_95(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ1_95) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_96(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ2_96) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_97(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ1_97) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_98(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ2_98) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXO_99(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXO_99) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_100(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_100) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_101(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_101) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXE_102(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXE_102) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_104(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_104) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_105(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_105) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXD_106(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXD_106) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_107(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_107) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_108(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_108) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXG_109(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXG_109) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_110(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_110) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_111(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_111) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXA_112(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXA_112) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXR_113(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXR_113) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isRXC_114(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_RXC_114) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isOBX_115(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_OBX_115) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isNTE_116(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_NTE_116) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ1_117(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ1_117) != NULL;
    } catch (...) {
    }
    return false;
  }
  bool isTQ2_118(size_t index = 0) {
    try {
      return this->getObject(index, RSP_Z86_TQ2_118) != NULL;
    } catch (...) {
    }
    return false;
  }
}; /* RSP_Z86_ */
} /* namespace HL7_281 */
#endif /*  __RSP_Z86__281_H__ */
