/*
 * hacca - C Toolkit for the HL7 Protocol
 *
 * Warning: This file was automatically generated by [hawk], please do not edit.
 *          Thu 25 Jun 18:58:51 CEST 2020
 *
 * R. Carbone (rocco@tecsiel.it)
 * Jun 2020
 *
 * SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * This file was developed as part of the ongoing activities related
 * to the design, implementation and execution of interoperability tests
 * between hacca-based versus AurigaHL7-based applications.
 *
 * In more details I decided to extend AurigaHL7 C++ Library with header files
 * implementing HL7 structures of the version 2.8.1 of the protocol (April 2014)
 * because the version 2.4 distributed with AurigaHL7 is a bit outdated (October 2000).
 *
 * All files in this fork was automatically generated by hacca-based tool [hawk]
 * and strictly follow the syntax and convention originally defined
 * by Auriga HL7 C++ Library just as form of continuity, convenience
 * and respect for their superb work.
 */


#ifndef __SCV_v281_H__
#define __SCV_v281_H__

#include "../../common/Util.h"
#include "../datatype/CWE.h"
#include "../datatype/ST.h"

namespace HL7_281 {

/* Scheduling Class Value Pair */
class SCV : public HL7Data {
 public:
  SCV() { this->init(); }

 private:
  /* Field ID */
  enum FIELD_ID {
    SCV_1, /* Parameter Class */
    SCV_2, /* Parameter Value */
    FIELD_ID_MAX
  };

 public:
  const char *className() const { return "SCV"; }
  SCV *create() const { return new SCV(); }

 private:
  void init() {
    setName("SCV");
    /* Init members */
    addObject<CWE>(SCV_1, "SCV.1", HL7::initialized, HL7::repetition_off);
    addObject<ST>(SCV_2, "SCV.2", HL7::initialized, HL7::repetition_off);
  }

 public:
  /* Getters */
  /****************************************
   * Parameter Class
   */
  CWE *getSCV_1(size_t index = 0) {
    return (CWE *)this->getObjectSafe(index, SCV_1);
  }

  CWE *getParameterClass(size_t index = 0) {
    return (CWE *)this->getObjectSafe(index, SCV_1);
  }

  bool isSCV_1(size_t index = 0) {
    try {
      return this->getObject(index, SCV_1) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isParameterClass(size_t index = 0) {
    try {
      return this->getObject(index, SCV_1) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Parameter Value
   */
  ST *getSCV_2(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, SCV_2);
  }

  ST *getParameterValue(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, SCV_2);
  }

  bool isSCV_2(size_t index = 0) {
    try {
      return this->getObject(index, SCV_2) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isParameterValue(size_t index = 0) {
    try {
      return this->getObject(index, SCV_2) != NULL;
    } catch (...) {
    }
    return false;
  }

}; /* End SCV */

} /* End HL7_281 */

#endif /* __SCV_v281_H__ */
