/*
 * hacca - C Toolkit for the HL7 Protocol
 *
 * Warning: This file was automatically generated by [hawk], please do not edit.
 *          Thu 25 Jun 18:58:54 CEST 2020
 *
 * R. Carbone (rocco@tecsiel.it)
 * Jun 2020
 *
 * SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * This file was developed as part of the ongoing activities related
 * to the design, implementation and execution of interoperability tests
 * between hacca-based versus AurigaHL7-based applications.
 *
 * In more details I decided to extend AurigaHL7 C++ Library with header files
 * implementing HL7 structures of the version 2.8.1 of the protocol (April 2014)
 * because the version 2.4 distributed with AurigaHL7 is a bit outdated (October 2000).
 *
 * All files in this fork was automatically generated by hacca-based tool [hawk]
 * and strictly follow the syntax and convention originally defined
 * by Auriga HL7 C++ Library just as form of continuity, convenience
 * and respect for their superb work.
 */


#ifndef __XON_v281_H__
#define __XON_v281_H__

#include "../../common/Util.h"
#include "../datatype/CWE.h"
#include "../datatype/HD.h"
#include "../datatype/ID.h"
#include "../datatype/ST.h"

namespace HL7_281 {

/* Extended Composite Name and Identification Number for Organizations */
class XON : public HL7Data {
 public:
  XON() { this->init(); }

 private:
  /* Field ID */
  enum FIELD_ID {
    XON_1, /* Organization Name */
    XON_2, /* Organization Name Type Code */
    XON_3, /* ID Number */
    XON_4, /* Identifier Check Digit */
    XON_5, /* Check Digit Scheme */
    XON_6, /* Assigning Authority */
    XON_7, /* Identifier Type Code */
    XON_8, /* Assigning Facility */
    XON_9, /* Name Representation Code */
    XON_10, /* Organization Identifier */
    FIELD_ID_MAX
  };

 public:
  const char *className() const { return "XON"; }
  XON *create() const { return new XON(); }

 private:
  void init() {
    setName("XON");
    /* Init members */
    addObject<ST>(XON_1, "XON.1", HL7::initialized, HL7::repetition_off);
    addObject<CWE>(XON_2, "XON.2", HL7::initialized, HL7::repetition_off);
    addObject<ST>(XON_3, "XON.3", HL7::initialized, HL7::repetition_off);
    addObject<ST>(XON_4, "XON.4", HL7::initialized, HL7::repetition_off);
    addObject<ST>(XON_5, "XON.5", HL7::initialized, HL7::repetition_off);
    addObject<HD>(XON_6, "XON.6", HL7::initialized, HL7::repetition_off);
    addObject<ID>(XON_7, "XON.7", HL7::initialized, HL7::repetition_off);
    addObject<HD>(XON_8, "XON.8", HL7::initialized, HL7::repetition_off);
    addObject<ID>(XON_9, "XON.9", HL7::initialized, HL7::repetition_off);
    addObject<ST>(XON_10, "XON.10", HL7::initialized, HL7::repetition_off);
  }

 public:
  /* Getters */
  /****************************************
   * Organization Name
   */
  ST *getXON_1(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XON_1);
  }

  ST *getOrganizationName(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XON_1);
  }

  bool isXON_1(size_t index = 0) {
    try {
      return this->getObject(index, XON_1) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isOrganizationName(size_t index = 0) {
    try {
      return this->getObject(index, XON_1) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Organization Name Type Code
   */
  CWE *getXON_2(size_t index = 0) {
    return (CWE *)this->getObjectSafe(index, XON_2);
  }

  CWE *getOrganizationNameTypeCode(size_t index = 0) {
    return (CWE *)this->getObjectSafe(index, XON_2);
  }

  bool isXON_2(size_t index = 0) {
    try {
      return this->getObject(index, XON_2) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isOrganizationNameTypeCode(size_t index = 0) {
    try {
      return this->getObject(index, XON_2) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * ID Number
   */
  ST *getXON_3(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XON_3);
  }

  ST *getIDNumber(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XON_3);
  }

  bool isXON_3(size_t index = 0) {
    try {
      return this->getObject(index, XON_3) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isIDNumber(size_t index = 0) {
    try {
      return this->getObject(index, XON_3) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Identifier Check Digit
   */
  ST *getXON_4(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XON_4);
  }

  ST *getIdentifierCheckDigit(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XON_4);
  }

  bool isXON_4(size_t index = 0) {
    try {
      return this->getObject(index, XON_4) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isIdentifierCheckDigit(size_t index = 0) {
    try {
      return this->getObject(index, XON_4) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Check Digit Scheme
   */
  ST *getXON_5(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XON_5);
  }

  ST *getCheckDigitScheme(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XON_5);
  }

  bool isXON_5(size_t index = 0) {
    try {
      return this->getObject(index, XON_5) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isCheckDigitScheme(size_t index = 0) {
    try {
      return this->getObject(index, XON_5) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Assigning Authority
   */
  HD *getXON_6(size_t index = 0) {
    return (HD *)this->getObjectSafe(index, XON_6);
  }

  HD *getAssigningAuthority(size_t index = 0) {
    return (HD *)this->getObjectSafe(index, XON_6);
  }

  bool isXON_6(size_t index = 0) {
    try {
      return this->getObject(index, XON_6) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isAssigningAuthority(size_t index = 0) {
    try {
      return this->getObject(index, XON_6) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Identifier Type Code
   */
  ID *getXON_7(size_t index = 0) {
    return (ID *)this->getObjectSafe(index, XON_7);
  }

  ID *getIdentifierTypeCode(size_t index = 0) {
    return (ID *)this->getObjectSafe(index, XON_7);
  }

  bool isXON_7(size_t index = 0) {
    try {
      return this->getObject(index, XON_7) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isIdentifierTypeCode(size_t index = 0) {
    try {
      return this->getObject(index, XON_7) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Assigning Facility
   */
  HD *getXON_8(size_t index = 0) {
    return (HD *)this->getObjectSafe(index, XON_8);
  }

  HD *getAssigningFacility(size_t index = 0) {
    return (HD *)this->getObjectSafe(index, XON_8);
  }

  bool isXON_8(size_t index = 0) {
    try {
      return this->getObject(index, XON_8) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isAssigningFacility(size_t index = 0) {
    try {
      return this->getObject(index, XON_8) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Name Representation Code
   */
  ID *getXON_9(size_t index = 0) {
    return (ID *)this->getObjectSafe(index, XON_9);
  }

  ID *getNameRepresentationCode(size_t index = 0) {
    return (ID *)this->getObjectSafe(index, XON_9);
  }

  bool isXON_9(size_t index = 0) {
    try {
      return this->getObject(index, XON_9) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isNameRepresentationCode(size_t index = 0) {
    try {
      return this->getObject(index, XON_9) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Organization Identifier
   */
  ST *getXON_10(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XON_10);
  }

  ST *getOrganizationIdentifier(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XON_10);
  }

  bool isXON_10(size_t index = 0) {
    try {
      return this->getObject(index, XON_10) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isOrganizationIdentifier(size_t index = 0) {
    try {
      return this->getObject(index, XON_10) != NULL;
    } catch (...) {
    }
    return false;
  }

}; /* End XON */

} /* End HL7_281 */

#endif /* __XON_v281_H__ */
