/*
 * hacca - C Toolkit for the HL7 Protocol
 *
 * Warning: This file was automatically generated by [hawk], please do not edit.
 *          Thu 25 Jun 18:58:55 CEST 2020
 *
 * R. Carbone (rocco@tecsiel.it)
 * Jun 2020
 *
 * SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * This file was developed as part of the ongoing activities related
 * to the design, implementation and execution of interoperability tests
 * between hacca-based versus AurigaHL7-based applications.
 *
 * In more details I decided to extend AurigaHL7 C++ Library with header files
 * implementing HL7 structures of the version 2.8.1 of the protocol (April 2014)
 * because the version 2.4 distributed with AurigaHL7 is a bit outdated (October 2000).
 *
 * All files in this fork was automatically generated by hacca-based tool [hawk]
 * and strictly follow the syntax and convention originally defined
 * by Auriga HL7 C++ Library just as form of continuity, convenience
 * and respect for their superb work.
 */


#ifndef __XPN_v281_H__
#define __XPN_v281_H__

#include "../../common/Util.h"
#include "../datatype/CWE.h"
#include "../datatype/DTM.h"
#include "../datatype/FN.h"
#include "../datatype/ID.h"
#include "../datatype/ST.h"

namespace HL7_281 {

/* Extended Person Name */
class XPN : public HL7Data {
 public:
  XPN() { this->init(); }

 private:
  /* Field ID */
  enum FIELD_ID {
    XPN_1, /* Family Name */
    XPN_2, /* Given Name */
    XPN_3, /* Second and Further Given Names or Initials Thereof */
    XPN_4, /* Suffix */
    XPN_5, /* Prefix */
    XPN_6, /* Degree */
    XPN_7, /* Name Type Code */
    XPN_8, /* Name Representation Code */
    XPN_9, /* Name Context */
    XPN_10, /* Name Validity Range */
    XPN_11, /* Name Assembly Order */
    XPN_12, /* Effective Date */
    XPN_13, /* Expiration Date */
    XPN_14, /* Professional Suffix */
    XPN_15, /* Called By */
    FIELD_ID_MAX
  };

 public:
  const char *className() const { return "XPN"; }
  XPN *create() const { return new XPN(); }

 private:
  void init() {
    setName("XPN");
    /* Init members */
    addObject<FN>(XPN_1, "XPN.1", HL7::initialized, HL7::repetition_off);
    addObject<ST>(XPN_2, "XPN.2", HL7::initialized, HL7::repetition_off);
    addObject<ST>(XPN_3, "XPN.3", HL7::initialized, HL7::repetition_off);
    addObject<ST>(XPN_4, "XPN.4", HL7::initialized, HL7::repetition_off);
    addObject<ST>(XPN_5, "XPN.5", HL7::initialized, HL7::repetition_off);
    addObject<ST>(XPN_6, "XPN.6", HL7::initialized, HL7::repetition_off);
    addObject<ID>(XPN_7, "XPN.7", HL7::initialized, HL7::repetition_off);
    addObject<ID>(XPN_8, "XPN.8", HL7::initialized, HL7::repetition_off);
    addObject<CWE>(XPN_9, "XPN.9", HL7::initialized, HL7::repetition_off);
    addObject<ST>(XPN_10, "XPN.10", HL7::initialized, HL7::repetition_off);
    addObject<ID>(XPN_11, "XPN.11", HL7::initialized, HL7::repetition_off);
    addObject<DTM>(XPN_12, "XPN.12", HL7::initialized, HL7::repetition_off);
    addObject<DTM>(XPN_13, "XPN.13", HL7::initialized, HL7::repetition_off);
    addObject<ST>(XPN_14, "XPN.14", HL7::initialized, HL7::repetition_off);
    addObject<ST>(XPN_15, "XPN.15", HL7::initialized, HL7::repetition_off);
  }

 public:
  /* Getters */
  /****************************************
   * Family Name
   */
  FN *getXPN_1(size_t index = 0) {
    return (FN *)this->getObjectSafe(index, XPN_1);
  }

  FN *getFamilyName(size_t index = 0) {
    return (FN *)this->getObjectSafe(index, XPN_1);
  }

  bool isXPN_1(size_t index = 0) {
    try {
      return this->getObject(index, XPN_1) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isFamilyName(size_t index = 0) {
    try {
      return this->getObject(index, XPN_1) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Given Name
   */
  ST *getXPN_2(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XPN_2);
  }

  ST *getGivenName(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XPN_2);
  }

  bool isXPN_2(size_t index = 0) {
    try {
      return this->getObject(index, XPN_2) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isGivenName(size_t index = 0) {
    try {
      return this->getObject(index, XPN_2) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Second and Further Given Names or Initials Thereof
   */
  ST *getXPN_3(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XPN_3);
  }

  ST *getSecondandFurtherGivenNamesorInitialsThereof(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XPN_3);
  }

  bool isXPN_3(size_t index = 0) {
    try {
      return this->getObject(index, XPN_3) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isSecondandFurtherGivenNamesorInitialsThereof(size_t index = 0) {
    try {
      return this->getObject(index, XPN_3) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Suffix
   */
  ST *getXPN_4(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XPN_4);
  }

  ST *getSuffix(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XPN_4);
  }

  bool isXPN_4(size_t index = 0) {
    try {
      return this->getObject(index, XPN_4) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isSuffix(size_t index = 0) {
    try {
      return this->getObject(index, XPN_4) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Prefix
   */
  ST *getXPN_5(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XPN_5);
  }

  ST *getPrefix(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XPN_5);
  }

  bool isXPN_5(size_t index = 0) {
    try {
      return this->getObject(index, XPN_5) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isPrefix(size_t index = 0) {
    try {
      return this->getObject(index, XPN_5) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Degree
   */
  ST *getXPN_6(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XPN_6);
  }

  ST *getDegree(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XPN_6);
  }

  bool isXPN_6(size_t index = 0) {
    try {
      return this->getObject(index, XPN_6) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isDegree(size_t index = 0) {
    try {
      return this->getObject(index, XPN_6) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Name Type Code
   */
  ID *getXPN_7(size_t index = 0) {
    return (ID *)this->getObjectSafe(index, XPN_7);
  }

  ID *getNameTypeCode(size_t index = 0) {
    return (ID *)this->getObjectSafe(index, XPN_7);
  }

  bool isXPN_7(size_t index = 0) {
    try {
      return this->getObject(index, XPN_7) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isNameTypeCode(size_t index = 0) {
    try {
      return this->getObject(index, XPN_7) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Name Representation Code
   */
  ID *getXPN_8(size_t index = 0) {
    return (ID *)this->getObjectSafe(index, XPN_8);
  }

  ID *getNameRepresentationCode(size_t index = 0) {
    return (ID *)this->getObjectSafe(index, XPN_8);
  }

  bool isXPN_8(size_t index = 0) {
    try {
      return this->getObject(index, XPN_8) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isNameRepresentationCode(size_t index = 0) {
    try {
      return this->getObject(index, XPN_8) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Name Context
   */
  CWE *getXPN_9(size_t index = 0) {
    return (CWE *)this->getObjectSafe(index, XPN_9);
  }

  CWE *getNameContext(size_t index = 0) {
    return (CWE *)this->getObjectSafe(index, XPN_9);
  }

  bool isXPN_9(size_t index = 0) {
    try {
      return this->getObject(index, XPN_9) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isNameContext(size_t index = 0) {
    try {
      return this->getObject(index, XPN_9) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Name Validity Range
   */
  ST *getXPN_10(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XPN_10);
  }

  ST *getNameValidityRange(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XPN_10);
  }

  bool isXPN_10(size_t index = 0) {
    try {
      return this->getObject(index, XPN_10) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isNameValidityRange(size_t index = 0) {
    try {
      return this->getObject(index, XPN_10) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Name Assembly Order
   */
  ID *getXPN_11(size_t index = 0) {
    return (ID *)this->getObjectSafe(index, XPN_11);
  }

  ID *getNameAssemblyOrder(size_t index = 0) {
    return (ID *)this->getObjectSafe(index, XPN_11);
  }

  bool isXPN_11(size_t index = 0) {
    try {
      return this->getObject(index, XPN_11) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isNameAssemblyOrder(size_t index = 0) {
    try {
      return this->getObject(index, XPN_11) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Effective Date
   */
  DTM *getXPN_12(size_t index = 0) {
    return (DTM *)this->getObjectSafe(index, XPN_12);
  }

  DTM *getEffectiveDate(size_t index = 0) {
    return (DTM *)this->getObjectSafe(index, XPN_12);
  }

  bool isXPN_12(size_t index = 0) {
    try {
      return this->getObject(index, XPN_12) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isEffectiveDate(size_t index = 0) {
    try {
      return this->getObject(index, XPN_12) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Expiration Date
   */
  DTM *getXPN_13(size_t index = 0) {
    return (DTM *)this->getObjectSafe(index, XPN_13);
  }

  DTM *getExpirationDate(size_t index = 0) {
    return (DTM *)this->getObjectSafe(index, XPN_13);
  }

  bool isXPN_13(size_t index = 0) {
    try {
      return this->getObject(index, XPN_13) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isExpirationDate(size_t index = 0) {
    try {
      return this->getObject(index, XPN_13) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Professional Suffix
   */
  ST *getXPN_14(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XPN_14);
  }

  ST *getProfessionalSuffix(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XPN_14);
  }

  bool isXPN_14(size_t index = 0) {
    try {
      return this->getObject(index, XPN_14) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isProfessionalSuffix(size_t index = 0) {
    try {
      return this->getObject(index, XPN_14) != NULL;
    } catch (...) {
    }
    return false;
  }

  /****************************************
   * Called By
   */
  ST *getXPN_15(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XPN_15);
  }

  ST *getCalledBy(size_t index = 0) {
    return (ST *)this->getObjectSafe(index, XPN_15);
  }

  bool isXPN_15(size_t index = 0) {
    try {
      return this->getObject(index, XPN_15) != NULL;
    } catch (...) {
    }
    return false;
  }

  bool isCalledBy(size_t index = 0) {
    try {
      return this->getObject(index, XPN_15) != NULL;
    } catch (...) {
    }
    return false;
  }

}; /* End XPN */

} /* End HL7_281 */

#endif /* __XPN_v281_H__ */
